// Package httpadapter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpadapter

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorEnvelopeVersion.
const (
	TalariaErrorV1 ErrorEnvelopeVersion = "talaria.error.v1"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeVersion enum.
func (e ErrorEnvelopeVersion) Valid() bool {
	switch e {
	case TalariaErrorV1:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationLifecycle.
const (
	ExplanationLifecycleActive      ExplanationLifecycle = "active"
	ExplanationLifecycleForgotten   ExplanationLifecycle = "forgotten"
	ExplanationLifecyclePurged      ExplanationLifecycle = "purged"
	ExplanationLifecycleQuarantined ExplanationLifecycle = "quarantined"
)

// Valid indicates whether the value is a known member of the ExplanationLifecycle enum.
func (e ExplanationLifecycle) Valid() bool {
	switch e {
	case ExplanationLifecycleActive:
		return true
	case ExplanationLifecycleForgotten:
		return true
	case ExplanationLifecyclePurged:
		return true
	case ExplanationLifecycleQuarantined:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationResolutionState.
const (
	ExplanationResolutionStateOpen     ExplanationResolutionState = "open"
	ExplanationResolutionStateResolved ExplanationResolutionState = "resolved"
)

// Valid indicates whether the value is a known member of the ExplanationResolutionState enum.
func (e ExplanationResolutionState) Valid() bool {
	switch e {
	case ExplanationResolutionStateOpen:
		return true
	case ExplanationResolutionStateResolved:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationTrust.
const (
	ExplanationTrustUnverified ExplanationTrust = "unverified"
	ExplanationTrustVerified   ExplanationTrust = "verified"
)

// Valid indicates whether the value is a known member of the ExplanationTrust enum.
func (e ExplanationTrust) Valid() bool {
	switch e {
	case ExplanationTrustUnverified:
		return true
	case ExplanationTrustVerified:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseVersion.
const (
	TalariaHealthV1 HealthResponseVersion = "talaria.health.v1"
)

// Valid indicates whether the value is a known member of the HealthResponseVersion enum.
func (e HealthResponseVersion) Valid() bool {
	switch e {
	case TalariaHealthV1:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemKind.
const (
	Failure             MemoryItemKind = "failure"
	Procedure           MemoryItemKind = "procedure"
	StandingInstruction MemoryItemKind = "standing_instruction"
	State               MemoryItemKind = "state"
)

// Valid indicates whether the value is a known member of the MemoryItemKind enum.
func (e MemoryItemKind) Valid() bool {
	switch e {
	case Failure:
		return true
	case Procedure:
		return true
	case StandingInstruction:
		return true
	case State:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemLifecycle.
const (
	MemoryItemLifecycleActive MemoryItemLifecycle = "active"
)

// Valid indicates whether the value is a known member of the MemoryItemLifecycle enum.
func (e MemoryItemLifecycle) Valid() bool {
	switch e {
	case MemoryItemLifecycleActive:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemResolutionState.
const (
	MemoryItemResolutionStateOpen     MemoryItemResolutionState = "open"
	MemoryItemResolutionStateResolved MemoryItemResolutionState = "resolved"
)

// Valid indicates whether the value is a known member of the MemoryItemResolutionState enum.
func (e MemoryItemResolutionState) Valid() bool {
	switch e {
	case MemoryItemResolutionStateOpen:
		return true
	case MemoryItemResolutionStateResolved:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemTrust.
const (
	MemoryItemTrustVerified MemoryItemTrust = "verified"
)

// Valid indicates whether the value is a known member of the MemoryItemTrust enum.
func (e MemoryItemTrust) Valid() bool {
	switch e {
	case MemoryItemTrustVerified:
		return true
	default:
		return false
	}
}

// Defines values for MemorySearchResponseVersion.
const (
	TalariaMemorySearchV1 MemorySearchResponseVersion = "talaria.memory-search.v1"
)

// Valid indicates whether the value is a known member of the MemorySearchResponseVersion enum.
func (e MemorySearchResponseVersion) Valid() bool {
	switch e {
	case TalariaMemorySearchV1:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseVersion.
const (
	TalariaReadyV1 ReadinessResponseVersion = "talaria.ready.v1"
)

// Valid indicates whether the value is a known member of the ReadinessResponseVersion enum.
func (e ReadinessResponseVersion) Valid() bool {
	switch e {
	case TalariaReadyV1:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartHookSpecificOutputHookEventName.
const (
	SessionStartHookSpecificOutputHookEventNameSessionStart SessionStartHookSpecificOutputHookEventName = "SessionStart"
)

// Valid indicates whether the value is a known member of the SessionStartHookSpecificOutputHookEventName enum.
func (e SessionStartHookSpecificOutputHookEventName) Valid() bool {
	switch e {
	case SessionStartHookSpecificOutputHookEventNameSessionStart:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartRequestHookEventName.
const (
	SessionStartRequestHookEventNameSessionStart SessionStartRequestHookEventName = "SessionStart"
)

// Valid indicates whether the value is a known member of the SessionStartRequestHookEventName enum.
func (e SessionStartRequestHookEventName) Valid() bool {
	switch e {
	case SessionStartRequestHookEventNameSessionStart:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartResponseVersion.
const (
	TalariaSessionStartV1 SessionStartResponseVersion = "talaria.session-start.v1"
)

// Valid indicates whether the value is a known member of the SessionStartResponseVersion enum.
func (e SessionStartResponseVersion) Valid() bool {
	switch e {
	case TalariaSessionStartV1:
		return true
	default:
		return false
	}
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      string               `json:"code"`
	Message   string               `json:"message"`
	ReceiptId openapi_types.UUID   `json:"receipt_id"`
	Retryable bool                 `json:"retryable"`
	Version   ErrorEnvelopeVersion `json:"version"`
}

// ErrorEnvelopeVersion defines model for ErrorEnvelope.Version.
type ErrorEnvelopeVersion string

// Explanation defines model for Explanation.
type Explanation struct {
	CreatedAt       time.Time                   `json:"created_at"`
	Lifecycle       ExplanationLifecycle        `json:"lifecycle"`
	MemoryId        openapi_types.UUID          `json:"memory_id"`
	Pinned          bool                        `json:"pinned"`
	ResolutionState *ExplanationResolutionState `json:"resolution_state,omitempty"`
	RevisionId      openapi_types.UUID          `json:"revision_id"`
	Trust           ExplanationTrust            `json:"trust"`
	UpdatedAt       time.Time                   `json:"updated_at"`
}

// ExplanationLifecycle defines model for Explanation.Lifecycle.
type ExplanationLifecycle string

// ExplanationResolutionState defines model for Explanation.ResolutionState.
type ExplanationResolutionState string

// ExplanationTrust defines model for Explanation.Trust.
type ExplanationTrust string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus  `json:"status"`
	Version HealthResponseVersion `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HealthResponseVersion defines model for HealthResponse.Version.
type HealthResponseVersion string

// MemoryItem defines model for MemoryItem.
type MemoryItem struct {
	Content         string                     `json:"content"`
	Kind            MemoryItemKind             `json:"kind"`
	Lifecycle       MemoryItemLifecycle        `json:"lifecycle"`
	MemoryId        openapi_types.UUID         `json:"memory_id"`
	ResolutionState *MemoryItemResolutionState `json:"resolution_state,omitempty"`
	RevisionId      openapi_types.UUID         `json:"revision_id"`
	Score           *float32                   `json:"score,omitempty"`
	Tags            []string                   `json:"tags"`
	Title           string                     `json:"title"`
	Trust           MemoryItemTrust            `json:"trust"`
	WorkspaceId     string                     `json:"workspace_id"`
}

// MemoryItemKind defines model for MemoryItem.Kind.
type MemoryItemKind string

// MemoryItemLifecycle defines model for MemoryItem.Lifecycle.
type MemoryItemLifecycle string

// MemoryItemResolutionState defines model for MemoryItem.ResolutionState.
type MemoryItemResolutionState string

// MemoryItemTrust defines model for MemoryItem.Trust.
type MemoryItemTrust string

// MemorySearchRequest defines model for MemorySearchRequest.
type MemorySearchRequest struct {
	Limit       *int   `json:"limit,omitempty"`
	Query       string `json:"query"`
	SessionId   string `json:"session_id"`
	WorkspaceId string `json:"workspace_id"`
}

// MemorySearchResponse defines model for MemorySearchResponse.
type MemorySearchResponse struct {
	Included  int                         `json:"included"`
	Items     []MemoryItem                `json:"items"`
	Omitted   int                         `json:"omitted"`
	ReceiptId openapi_types.UUID          `json:"receipt_id"`
	Version   MemorySearchResponseVersion `json:"version"`
}

// MemorySearchResponseVersion defines model for MemorySearchResponse.Version.
type MemorySearchResponseVersion string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Ready   bool                     `json:"ready"`
	Reason  *string                  `json:"reason,omitempty"`
	Version ReadinessResponseVersion `json:"version"`
}

// ReadinessResponseVersion defines model for ReadinessResponse.Version.
type ReadinessResponseVersion string

// SessionStartHookSpecificOutput defines model for SessionStartHookSpecificOutput.
type SessionStartHookSpecificOutput struct {
	AdditionalContext string                                      `json:"additionalContext"`
	HookEventName     SessionStartHookSpecificOutputHookEventName `json:"hookEventName"`
}

// SessionStartHookSpecificOutputHookEventName defines model for SessionStartHookSpecificOutput.HookEventName.
type SessionStartHookSpecificOutputHookEventName string

// SessionStartRequest Raw Codex SessionStart event. Unknown fields are ignored and are never retained by the application.
type SessionStartRequest struct {
	Cwd                  string                           `json:"cwd"`
	HookEventName        SessionStartRequestHookEventName `json:"hook_event_name"`
	SessionId            string                           `json:"session_id"`
	AdditionalProperties map[string]interface{}           `json:"-"`
}

// SessionStartRequestHookEventName defines model for SessionStartRequest.HookEventName.
type SessionStartRequestHookEventName string

// SessionStartResponse defines model for SessionStartResponse.
type SessionStartResponse struct {
	HookSpecificOutput SessionStartHookSpecificOutput `json:"hookSpecificOutput"`
	Included           int                            `json:"included"`
	Items              []MemoryItem                   `json:"items"`
	NextCursor         *string                        `json:"next_cursor,omitempty"`
	Omitted            int                            `json:"omitted"`
	Version            SessionStartResponseVersion    `json:"version"`
	Warning            *string                        `json:"warning,omitempty"`
	WorkspaceId        string                         `json:"workspace_id"`
}

// SessionStartResponseVersion defines model for SessionStartResponse.Version.
type SessionStartResponseVersion string

// MemoryID defines model for MemoryID.
type MemoryID = openapi_types.UUID

// WorkspaceID defines model for WorkspaceID.
type WorkspaceID = string

// MemoryGetParams defines parameters for MemoryGet.
type MemoryGetParams struct {
	WorkspaceId WorkspaceID `form:"workspace_id" json:"workspace_id"`
}

// MemorySearchJSONRequestBody defines body for MemorySearch for application/json ContentType.
type MemorySearchJSONRequestBody = MemorySearchRequest

// SessionStartJSONRequestBody defines body for SessionStart for application/json ContentType.
type SessionStartJSONRequestBody = SessionStartRequest

// Getter for additional properties for SessionStartRequest. Returns the specified
// element and whether it was found
func (a SessionStartRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionStartRequest
func (a *SessionStartRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionStartRequest to handle AdditionalProperties
func (a *SessionStartRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cwd"]; found {
		err = json.Unmarshal(raw, &a.Cwd)
		if err != nil {
			return fmt.Errorf("error reading 'cwd': %w", err)
		}
		delete(object, "cwd")
	}

	if raw, found := object["hook_event_name"]; found {
		err = json.Unmarshal(raw, &a.HookEventName)
		if err != nil {
			return fmt.Errorf("error reading 'hook_event_name': %w", err)
		}
		delete(object, "hook_event_name")
	}

	if raw, found := object["session_id"]; found {
		err = json.Unmarshal(raw, &a.SessionId)
		if err != nil {
			return fmt.Errorf("error reading 'session_id': %w", err)
		}
		delete(object, "session_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionStartRequest to handle AdditionalProperties
func (a SessionStartRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["cwd"], err = json.Marshal(a.Cwd)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cwd': %w", err)
	}

	object["hook_event_name"], err = json.Marshal(a.HookEventName)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'hook_event_name': %w", err)
	}

	object["session_id"], err = json.Marshal(a.SessionId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'session_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFjdcts8Dn0VDncvFf81bXd913az28y0206yPxeZTAaWYJu1RCog5Nhfxu/+DUnZkmw5ttMm0zvLosiD",
	"A+AAxKOMTZYbjZqtHD7KHAgyZCT/9BUzQ8vLf7jfSsuhzIGnMpIaMpRDmfnXdyqRkSS8LxRhIodMBUbS",
	"xlPMwH04NpQBy6EsCr+Sl7n72DIpPZGrVST/b2hmc4ixdtJ9gbSsjnpYLzl0WgaLL6gnPJXDwdt3kcyU",
	"Xj/3d89erT/15l4QGbrQc0yNW/YoIUkUK6Mh/U4mR2KFVg7HkFqMZF77y9GY+E+ePC+SGVoLk2NWEsao",
	"cnb2HibRLWdawij1W5dvR8akCNq9niNZZXRAqq3biSEFUtBBZ3Vn3m91TUX0zWaPKBhbGdMAW4dyu9nS",
	"jH5gzA7JxSJPQQOXaE6hmBAYkzvHQ42RBBjPWGXYRkuqxhgv40AL6iJzhkDMau6W3xdAoFlpdLjHhiaG",
	"GZ2FeUETTGoG1F24jvpj/JIr7XZvdQqhNWnhrL+zDNzAaHKPwy+Z70FCOFfOI8diYSos1w+ZI6mx8sYX",
	"evPQdlSRJydyvxU8Ta2ocK9R1V21YS2q+7wBoi2yPiOkPL1CmxttT81f54DC1vPDzNo4fCKRpv78YzKp",
	"PKzarc2cUnwZs5OlSDNq3lLDv/X/PmixZ6Z0Ug+JEIh+yxiTgtzvMag0/LIMOlF6cqe0ZSpiboI/Lu9+",
	"PqleO3FsbKgurLrIRkg+pWDiOVeMmd1i/N15m6GwuAxrB73NayCCpd9OcaBsu4ydkMttBjfKZ2XHybm6",
	"VYZ98KxRR5vAK2lpS+39gX6NQPH0Cu8LDIadEPGpypT/JsExFCnLYb/nqVaZI8cxnSkdHqpaqzTjJLgx",
	"dBtN3vu9wXl0qEpbtLVAOqn52PXKab1L02frfmnLQzV8h6l/lnAqHadFEkrchuReG8mbHNn8+CvhWA7l",
	"X7pVE9ot+7FuTf4Opo3JFPMxEE5sqp4Q+5AjZ9ZTd1r3FMyPKuYqAxoI2xx2hZAojdY+01uEkCz3dSNg",
	"g62n8OA3PMb+cPLTJe86ROs1A/FnY2bXOcZqrOJvBefFqaJQLf3kdGnBRzTdU2NmF3PU/G9/7ajMrSM7",
	"aGpzl6gFySHjD8pguPYkaGNSeeil5RU8iE8mwYWobyXQIemI/+qZNg9ajBWmiRVAKNREG8JEgE78s8Y5",
	"kiBkcB2xGC0FT1FAnqcq9g17R+70Gg/byvW2P4iOofnO47rTJxH9U4K73YRVO+0iirxlh930rCSctob2",
	"U2J4IDFW0W8hwxoXfBcXZA21ysjRMv2E3pReO7OOilbdieQDkHY/2zCc1glVor1VV5/U8Bb/7kaSj+W4",
	"IMXLa8d1CI0RAiF9KFwEr5/+uS5TJof7wrfh/gMn335BxcGUOQ9jDaXHJnREdYlwG6Nml86YRCI1Jh9B",
	"PDszOl0K176RSYUtaAwxirEhLwCpiSEVoeCJBDALQlD2qvI/wTNnXzErl643+vD9sib4Q9nr9DoDHwg5",
	"asiVHMo3nX6n51QFeOoJ6JYfd+f9bjiyG2qsn06ZoIkumbwgXSZy2GhiytkQWv5oQqGr3YZqStb9Uda6",
	"anJ0OAuaLeqqGSxOkcPVxEuCN2bQ670QhFJ3PIami/9X3gMiYWPQGuls4pwtAouC0BYp245zw/kvhNec",
	"nbXhglQlfmdR3ic7btkqanP54+YKsnIHT3Cv2/+F7MOnGlvetAOtlnQ3Y81VdHBtfTa5un1x/wah3WXv",
	"m0Yx3+PZwFXp0fPX82hALLRhMTaFToTSXi/KBHQxF5v8SDd3cZGnoPQBd1+Uq57v8pf0YX222ULYNYxR",
	"EOiZ0hPfdG3uxSJDhgQY2shqlLz9MrjVOb2EDLa1qK8sg63tVwvXH11EYrJJGl+UcMHCYopxaGZ/Cwl0",
	"GPqvh6HWAezg6L95PRxl+IiRSZYCFzFiYr16lCMcYTSKr+qj8LMdj+9t7xXxXSPNVYxCWVFomINKYZSi",
	"MLQWX+Enj+690u6AFLmSujAK/mOvmH0u379gomxNw1tM/E4mRmudCZCquUdfNaVyeHPrbfEX9/2mXIXX",
	"L2jJ7syjzV9sCCa4qY2RF9iczI+Q7f6CG4YVvzqWjsK3TbYYFexL5xpTiJwa+83LwM2tq1wWab6ueM39",
	"vyhGgnTT0gvX0stIFpSW94Jht9sfvO+4Jrw/fH/+5r1c3a7+DAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
