// Package httpadapter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpadapter

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorEnvelopeVersion.
const (
	TalariaErrorV1 ErrorEnvelopeVersion = "talaria.error.v1"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeVersion enum.
func (e ErrorEnvelopeVersion) Valid() bool {
	switch e {
	case TalariaErrorV1:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationLifecycle.
const (
	ExplanationLifecycleActive      ExplanationLifecycle = "active"
	ExplanationLifecycleForgotten   ExplanationLifecycle = "forgotten"
	ExplanationLifecyclePurged      ExplanationLifecycle = "purged"
	ExplanationLifecycleQuarantined ExplanationLifecycle = "quarantined"
)

// Valid indicates whether the value is a known member of the ExplanationLifecycle enum.
func (e ExplanationLifecycle) Valid() bool {
	switch e {
	case ExplanationLifecycleActive:
		return true
	case ExplanationLifecycleForgotten:
		return true
	case ExplanationLifecyclePurged:
		return true
	case ExplanationLifecycleQuarantined:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationResolutionState.
const (
	ExplanationResolutionStateOpen     ExplanationResolutionState = "open"
	ExplanationResolutionStateResolved ExplanationResolutionState = "resolved"
)

// Valid indicates whether the value is a known member of the ExplanationResolutionState enum.
func (e ExplanationResolutionState) Valid() bool {
	switch e {
	case ExplanationResolutionStateOpen:
		return true
	case ExplanationResolutionStateResolved:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationTrust.
const (
	ExplanationTrustUnverified ExplanationTrust = "unverified"
	ExplanationTrustVerified   ExplanationTrust = "verified"
)

// Valid indicates whether the value is a known member of the ExplanationTrust enum.
func (e ExplanationTrust) Valid() bool {
	switch e {
	case ExplanationTrustUnverified:
		return true
	case ExplanationTrustVerified:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseVersion.
const (
	TalariaHealthV1 HealthResponseVersion = "talaria.health.v1"
)

// Valid indicates whether the value is a known member of the HealthResponseVersion enum.
func (e HealthResponseVersion) Valid() bool {
	switch e {
	case TalariaHealthV1:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemKind.
const (
	Failure             MemoryItemKind = "failure"
	Procedure           MemoryItemKind = "procedure"
	StandingInstruction MemoryItemKind = "standing_instruction"
	State               MemoryItemKind = "state"
)

// Valid indicates whether the value is a known member of the MemoryItemKind enum.
func (e MemoryItemKind) Valid() bool {
	switch e {
	case Failure:
		return true
	case Procedure:
		return true
	case StandingInstruction:
		return true
	case State:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemLifecycle.
const (
	MemoryItemLifecycleActive MemoryItemLifecycle = "active"
)

// Valid indicates whether the value is a known member of the MemoryItemLifecycle enum.
func (e MemoryItemLifecycle) Valid() bool {
	switch e {
	case MemoryItemLifecycleActive:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemResolutionState.
const (
	MemoryItemResolutionStateOpen     MemoryItemResolutionState = "open"
	MemoryItemResolutionStateResolved MemoryItemResolutionState = "resolved"
)

// Valid indicates whether the value is a known member of the MemoryItemResolutionState enum.
func (e MemoryItemResolutionState) Valid() bool {
	switch e {
	case MemoryItemResolutionStateOpen:
		return true
	case MemoryItemResolutionStateResolved:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemTrust.
const (
	MemoryItemTrustVerified MemoryItemTrust = "verified"
)

// Valid indicates whether the value is a known member of the MemoryItemTrust enum.
func (e MemoryItemTrust) Valid() bool {
	switch e {
	case MemoryItemTrustVerified:
		return true
	default:
		return false
	}
}

// Defines values for MemorySearchResponseVersion.
const (
	TalariaMemorySearchV1 MemorySearchResponseVersion = "talaria.memory-search.v1"
)

// Valid indicates whether the value is a known member of the MemorySearchResponseVersion enum.
func (e MemorySearchResponseVersion) Valid() bool {
	switch e {
	case TalariaMemorySearchV1:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseVersion.
const (
	TalariaReadyV1 ReadinessResponseVersion = "talaria.ready.v1"
)

// Valid indicates whether the value is a known member of the ReadinessResponseVersion enum.
func (e ReadinessResponseVersion) Valid() bool {
	switch e {
	case TalariaReadyV1:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartResponseVersion.
const (
	TalariaSessionStartV1 SessionStartResponseVersion = "talaria.session-start.v1"
)

// Valid indicates whether the value is a known member of the SessionStartResponseVersion enum.
func (e SessionStartResponseVersion) Valid() bool {
	switch e {
	case TalariaSessionStartV1:
		return true
	default:
		return false
	}
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      string               `json:"code"`
	Message   string               `json:"message"`
	ReceiptId openapi_types.UUID   `json:"receipt_id"`
	Retryable bool                 `json:"retryable"`
	Version   ErrorEnvelopeVersion `json:"version"`
}

// ErrorEnvelopeVersion defines model for ErrorEnvelope.Version.
type ErrorEnvelopeVersion string

// Explanation defines model for Explanation.
type Explanation struct {
	CreatedAt       time.Time                   `json:"created_at"`
	Lifecycle       ExplanationLifecycle        `json:"lifecycle"`
	MemoryId        openapi_types.UUID          `json:"memory_id"`
	Pinned          bool                        `json:"pinned"`
	ResolutionState *ExplanationResolutionState `json:"resolution_state,omitempty"`
	RevisionId      openapi_types.UUID          `json:"revision_id"`
	Trust           ExplanationTrust            `json:"trust"`
	UpdatedAt       time.Time                   `json:"updated_at"`
}

// ExplanationLifecycle defines model for Explanation.Lifecycle.
type ExplanationLifecycle string

// ExplanationResolutionState defines model for Explanation.ResolutionState.
type ExplanationResolutionState string

// ExplanationTrust defines model for Explanation.Trust.
type ExplanationTrust string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus  `json:"status"`
	Version HealthResponseVersion `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HealthResponseVersion defines model for HealthResponse.Version.
type HealthResponseVersion string

// MemoryItem defines model for MemoryItem.
type MemoryItem struct {
	Content         string                     `json:"content"`
	Kind            MemoryItemKind             `json:"kind"`
	Lifecycle       MemoryItemLifecycle        `json:"lifecycle"`
	MemoryId        openapi_types.UUID         `json:"memory_id"`
	ResolutionState *MemoryItemResolutionState `json:"resolution_state,omitempty"`
	RevisionId      openapi_types.UUID         `json:"revision_id"`
	Score           *float32                   `json:"score,omitempty"`
	Tags            []string                   `json:"tags"`
	Title           string                     `json:"title"`
	Trust           MemoryItemTrust            `json:"trust"`
	WorkspaceId     string                     `json:"workspace_id"`
}

// MemoryItemKind defines model for MemoryItem.Kind.
type MemoryItemKind string

// MemoryItemLifecycle defines model for MemoryItem.Lifecycle.
type MemoryItemLifecycle string

// MemoryItemResolutionState defines model for MemoryItem.ResolutionState.
type MemoryItemResolutionState string

// MemoryItemTrust defines model for MemoryItem.Trust.
type MemoryItemTrust string

// MemorySearchRequest defines model for MemorySearchRequest.
type MemorySearchRequest struct {
	Limit       *int   `json:"limit,omitempty"`
	Query       string `json:"query"`
	SessionId   string `json:"session_id"`
	WorkspaceId string `json:"workspace_id"`
}

// MemorySearchResponse defines model for MemorySearchResponse.
type MemorySearchResponse struct {
	Included  int                         `json:"included"`
	Items     []MemoryItem                `json:"items"`
	Omitted   int                         `json:"omitted"`
	ReceiptId openapi_types.UUID          `json:"receipt_id"`
	Version   MemorySearchResponseVersion `json:"version"`
}

// MemorySearchResponseVersion defines model for MemorySearchResponse.Version.
type MemorySearchResponseVersion string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Ready   bool                     `json:"ready"`
	Reason  *string                  `json:"reason,omitempty"`
	Version ReadinessResponseVersion `json:"version"`
}

// ReadinessResponseVersion defines model for ReadinessResponse.Version.
type ReadinessResponseVersion string

// SessionStartRequest defines model for SessionStartRequest.
type SessionStartRequest struct {
	Query       *string `json:"query,omitempty"`
	SessionId   string  `json:"session_id"`
	WorkspaceId string  `json:"workspace_id"`
}

// SessionStartResponse defines model for SessionStartResponse.
type SessionStartResponse struct {
	Included    int                         `json:"included"`
	Items       []MemoryItem                `json:"items"`
	NextCursor  *string                     `json:"next_cursor,omitempty"`
	Omitted     int                         `json:"omitted"`
	Version     SessionStartResponseVersion `json:"version"`
	Warning     *string                     `json:"warning,omitempty"`
	WorkspaceId string                      `json:"workspace_id"`
}

// SessionStartResponseVersion defines model for SessionStartResponse.Version.
type SessionStartResponseVersion string

// MemoryID defines model for MemoryID.
type MemoryID = openapi_types.UUID

// WorkspaceID defines model for WorkspaceID.
type WorkspaceID = string

// MemoryGetParams defines parameters for MemoryGet.
type MemoryGetParams struct {
	WorkspaceId WorkspaceID `form:"workspace_id" json:"workspace_id"`
}

// MemorySearchJSONRequestBody defines body for MemorySearch for application/json ContentType.
type MemorySearchJSONRequestBody = MemorySearchRequest

// SessionStartJSONRequestBody defines body for SessionStart for application/json ContentType.
type SessionStartJSONRequestBody = SessionStartRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fhbb9u4Ev4rBM95VHxJ0/YcvbU4OdsALbZIFrsPQRCMpbHNRiKV4ci1N/B/X5CUdXHk2M42QffNsqjh",
	"N983N/JBJiYvjEbNVsYPsgCCHBnJP33B3NDq4n/ut9IylgXwXEZSQ44ylrl/fatSGUnC+1IRpjJmKjGS",
	"NpljDu7DqaEcWMayLP1KXhXuY8uk9Eyu15H8w9CdLSDB1k73JdKq2er7Zsm+3XJYfkY947mMT9++i2Su",
	"9OZ5/Hjv9eZT7+45kaFzvcDMuGUPEtJUsTIasq9kCiRWaGU8hcxiJIvWX47G1H/y5H6RzNFamB2ykjBB",
	"VbDzdz+JbjnTCiaZN129nRiTIWj3eoFkldEBqbbOEkMGpGCAzuvBYtwrTUP0dW0jCs42znTAtqHc1CbN",
	"5Bsm7JCcL4sMNHCF5hiKCYExvXU8tBhJgfGEVY59tGRqiskqCbSgLnPnCCSsFm75fQkEmpVGh3tqaGaY",
	"0XlYlDTDtOVAW8JN1B+iS6G0s94rCqE1Wem8v7UM3MFoCo/DL1nsQEK4UE6RQ7EwlZbbmyyQ1FR550td",
	"P/RtVRbpkdxvBU+3VjS4N6jaUtWsRW3NOyD6IusTQsbzS7SF0fbY/HUClLadH+auj8MnEmnu9z8kk6rN",
	"Gmt97lTFlzE/uhRpRs1b1fA/4/+e9vhzp3TaDokQiN5kgmlJ7vcUVBZ+WQadKj27VdoylQl3wR+Wd38/",
	"qV47cWxiqF1YdZlPkHxKwcxzrhhzu8X4u7M+R2F5EdaejurXQAQrb05xoGy7jR2Ry30Od9pn48fRubrV",
	"hn3wbFBHdeBVtPSl9u5Av0KgZH6J9yUGx46I+Ezlyn+T4hTKjGU8HnmqVe7IcUznSoeHptcqzTgLMoZp",
	"o8v7eHR6Fu3r0hZtK5COGj4eq3Lc7NLVbDMvbSnUwref+mcVTqWTrExDi6tJHvWRXOdI/ePfhFMZy38N",
	"myF0WM1jw1b525s2JlfMh0A4cqh6otiHHDmxnrrjpqfgftQw1zjQQdgn2CVCqjRa+0y1CCFd7ZpGwAZf",
	"j+HBGzzE/7Dz0y3vKkTrFQPx8yrB7kT+eVO3BWTL8H6O/rEpq3HJt0lJ1lBvyB2c0k/EZkXsiXVc9cZo",
	"JL8DafezD8NxXbNJ8K0a/ES+PxbYB2ZSkuLVlaM1KDZBIKQPpYunzdP/N9XLFHBf+unMf+Cy2i9o3J0z",
	"F+G0q/TUhEZpE1JFOIVJZxg1q8SN15HIjCkmkNydGJ2thOvqZDJhS5pCgmJqSPAcRWYSyESogyIFzI0e",
	"1MNALH8LIpx8wbxaujH04etFqw7EcjQYDcZe8wI1FErG8s1gPBi5KRR47gkYVh8PF+Nh2HIYSq+/tDCh",
	"TrgY9wfLi1TGnd5WXRmg5Y8m1L/WkAxFkTnXldHDb1UJbC4U9gd8d3JZd+OCqcQwsfpM9c6cjkYvBKEq",
	"Bx5DV+Lfq/EwEjYBrZFOZk5sEVgUhLbM2A6cDGc/EF73SqUPF2Qq9ZZFdcwYuGXrqE/yh3oyXbuNZ7hT",
	"9l+Qffg0t1nX/UCbJcP6tmsd7V3bvrJa37y4vqGmPmbvV41isUPZwFWl6NnrKRoQC21YTE2pU6G0rxdV",
	"ArqYS0xxoMxDXBYZKL1H7vNq1fMlf0kN21dePYRdwRQFgb5TeiZAp6I+LokcGVJg6COr0912l8H2vPBC",
	"ZbBvbHvlMtg7FfVw/dFFJKZ10vimhEsWFjP01xk/SQl0GMavh6E1ATzCMX7zejiq8BETk64ELhPE1Prq",
	"UZ3shdEovqiPwh/5Pb63o1fEd4W0UAkKZUWpYQEqg0mGwtCm+Ap/IeXeK+02yJCbUhduCP/cWcw+Ve9f",
	"MFG2Lkl7XPxKJkFrnQuQqYVH3wylMr6+8b7489xuVy7D6xf05PFRuE8vNgQzrHtj5AtsQeZbyHYB5DqT",
	"O8P+6Fg6CN822WJSsm+dG0whclrsdw8D1zeuc1mkxabjde1/VowEWT3SCzfSy0iWlFXngng4HJ++H/gh",
	"PH5/9ua9XN+s/woAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
