// Package httpadapter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpadapter

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CurationHookRequestHookEventName.
const (
	CurationHookRequestHookEventNamePreCompact       CurationHookRequestHookEventName = "PreCompact"
	CurationHookRequestHookEventNameSessionEnd       CurationHookRequestHookEventName = "SessionEnd"
	CurationHookRequestHookEventNameUserPromptSubmit CurationHookRequestHookEventName = "UserPromptSubmit"
)

// Valid indicates whether the value is a known member of the CurationHookRequestHookEventName enum.
func (e CurationHookRequestHookEventName) Valid() bool {
	switch e {
	case CurationHookRequestHookEventNamePreCompact:
		return true
	case CurationHookRequestHookEventNameSessionEnd:
		return true
	case CurationHookRequestHookEventNameUserPromptSubmit:
		return true
	default:
		return false
	}
}

// Defines values for CurationHookResponseHookEventName.
const (
	CurationHookResponseHookEventNamePreCompact       CurationHookResponseHookEventName = "PreCompact"
	CurationHookResponseHookEventNameSessionEnd       CurationHookResponseHookEventName = "SessionEnd"
	CurationHookResponseHookEventNameUserPromptSubmit CurationHookResponseHookEventName = "UserPromptSubmit"
)

// Valid indicates whether the value is a known member of the CurationHookResponseHookEventName enum.
func (e CurationHookResponseHookEventName) Valid() bool {
	switch e {
	case CurationHookResponseHookEventNamePreCompact:
		return true
	case CurationHookResponseHookEventNameSessionEnd:
		return true
	case CurationHookResponseHookEventNameUserPromptSubmit:
		return true
	default:
		return false
	}
}

// Defines values for CurationHookResponseVersion.
const (
	TalariaCurationHookV1 CurationHookResponseVersion = "talaria.curation-hook.v1"
)

// Valid indicates whether the value is a known member of the CurationHookResponseVersion enum.
func (e CurationHookResponseVersion) Valid() bool {
	switch e {
	case TalariaCurationHookV1:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeVersion.
const (
	TalariaErrorV1 ErrorEnvelopeVersion = "talaria.error.v1"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeVersion enum.
func (e ErrorEnvelopeVersion) Valid() bool {
	switch e {
	case TalariaErrorV1:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationLifecycle.
const (
	ExplanationLifecycleActive      ExplanationLifecycle = "active"
	ExplanationLifecycleForgotten   ExplanationLifecycle = "forgotten"
	ExplanationLifecyclePurged      ExplanationLifecycle = "purged"
	ExplanationLifecycleQuarantined ExplanationLifecycle = "quarantined"
)

// Valid indicates whether the value is a known member of the ExplanationLifecycle enum.
func (e ExplanationLifecycle) Valid() bool {
	switch e {
	case ExplanationLifecycleActive:
		return true
	case ExplanationLifecycleForgotten:
		return true
	case ExplanationLifecyclePurged:
		return true
	case ExplanationLifecycleQuarantined:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationResolutionState.
const (
	ExplanationResolutionStateOpen     ExplanationResolutionState = "open"
	ExplanationResolutionStateResolved ExplanationResolutionState = "resolved"
)

// Valid indicates whether the value is a known member of the ExplanationResolutionState enum.
func (e ExplanationResolutionState) Valid() bool {
	switch e {
	case ExplanationResolutionStateOpen:
		return true
	case ExplanationResolutionStateResolved:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationTrust.
const (
	ExplanationTrustUnverified ExplanationTrust = "unverified"
	ExplanationTrustVerified   ExplanationTrust = "verified"
)

// Valid indicates whether the value is a known member of the ExplanationTrust enum.
func (e ExplanationTrust) Valid() bool {
	switch e {
	case ExplanationTrustUnverified:
		return true
	case ExplanationTrustVerified:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseVersion.
const (
	TalariaHealthV1 HealthResponseVersion = "talaria.health.v1"
)

// Valid indicates whether the value is a known member of the HealthResponseVersion enum.
func (e HealthResponseVersion) Valid() bool {
	switch e {
	case TalariaHealthV1:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemKind.
const (
	MemoryItemKindFailure             MemoryItemKind = "failure"
	MemoryItemKindProcedure           MemoryItemKind = "procedure"
	MemoryItemKindStandingInstruction MemoryItemKind = "standing_instruction"
	MemoryItemKindState               MemoryItemKind = "state"
)

// Valid indicates whether the value is a known member of the MemoryItemKind enum.
func (e MemoryItemKind) Valid() bool {
	switch e {
	case MemoryItemKindFailure:
		return true
	case MemoryItemKindProcedure:
		return true
	case MemoryItemKindStandingInstruction:
		return true
	case MemoryItemKindState:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemLifecycle.
const (
	MemoryItemLifecycleActive MemoryItemLifecycle = "active"
)

// Valid indicates whether the value is a known member of the MemoryItemLifecycle enum.
func (e MemoryItemLifecycle) Valid() bool {
	switch e {
	case MemoryItemLifecycleActive:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemResolutionState.
const (
	MemoryItemResolutionStateOpen     MemoryItemResolutionState = "open"
	MemoryItemResolutionStateResolved MemoryItemResolutionState = "resolved"
)

// Valid indicates whether the value is a known member of the MemoryItemResolutionState enum.
func (e MemoryItemResolutionState) Valid() bool {
	switch e {
	case MemoryItemResolutionStateOpen:
		return true
	case MemoryItemResolutionStateResolved:
		return true
	default:
		return false
	}
}

// Defines values for MemoryItemTrust.
const (
	MemoryItemTrustVerified MemoryItemTrust = "verified"
)

// Valid indicates whether the value is a known member of the MemoryItemTrust enum.
func (e MemoryItemTrust) Valid() bool {
	switch e {
	case MemoryItemTrustVerified:
		return true
	default:
		return false
	}
}

// Defines values for MemorySearchResponseVersion.
const (
	TalariaMemorySearchV1 MemorySearchResponseVersion = "talaria.memory-search.v1"
)

// Valid indicates whether the value is a known member of the MemorySearchResponseVersion enum.
func (e MemorySearchResponseVersion) Valid() bool {
	switch e {
	case TalariaMemorySearchV1:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseVersion.
const (
	TalariaReadyV1 ReadinessResponseVersion = "talaria.ready.v1"
)

// Valid indicates whether the value is a known member of the ReadinessResponseVersion enum.
func (e ReadinessResponseVersion) Valid() bool {
	switch e {
	case TalariaReadyV1:
		return true
	default:
		return false
	}
}

// Defines values for RecallItemKind.
const (
	RecallItemKindFailure             RecallItemKind = "failure"
	RecallItemKindProcedure           RecallItemKind = "procedure"
	RecallItemKindStandingInstruction RecallItemKind = "standing_instruction"
	RecallItemKindState               RecallItemKind = "state"
)

// Valid indicates whether the value is a known member of the RecallItemKind enum.
func (e RecallItemKind) Valid() bool {
	switch e {
	case RecallItemKindFailure:
		return true
	case RecallItemKindProcedure:
		return true
	case RecallItemKindStandingInstruction:
		return true
	case RecallItemKindState:
		return true
	default:
		return false
	}
}

// Defines values for RecallItemTrust.
const (
	RecallItemTrustGenerated RecallItemTrust = "generated"
	RecallItemTrustVerified  RecallItemTrust = "verified"
)

// Valid indicates whether the value is a known member of the RecallItemTrust enum.
func (e RecallItemTrust) Valid() bool {
	switch e {
	case RecallItemTrustGenerated:
		return true
	case RecallItemTrustVerified:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartHookSpecificOutputHookEventName.
const (
	SessionStartHookSpecificOutputHookEventNameSessionStart SessionStartHookSpecificOutputHookEventName = "SessionStart"
)

// Valid indicates whether the value is a known member of the SessionStartHookSpecificOutputHookEventName enum.
func (e SessionStartHookSpecificOutputHookEventName) Valid() bool {
	switch e {
	case SessionStartHookSpecificOutputHookEventNameSessionStart:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartRequestHookEventName.
const (
	SessionStartRequestHookEventNameSessionStart SessionStartRequestHookEventName = "SessionStart"
)

// Valid indicates whether the value is a known member of the SessionStartRequestHookEventName enum.
func (e SessionStartRequestHookEventName) Valid() bool {
	switch e {
	case SessionStartRequestHookEventNameSessionStart:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartResponseVersion.
const (
	TalariaSessionStartV1 SessionStartResponseVersion = "talaria.session-start.v1"
)

// Valid indicates whether the value is a known member of the SessionStartResponseVersion enum.
func (e SessionStartResponseVersion) Valid() bool {
	switch e {
	case TalariaSessionStartV1:
		return true
	default:
		return false
	}
}

// CurationHookRequest defines model for CurationHookRequest.
type CurationHookRequest struct {
	CurrentPrompt        *string                          `json:"current_prompt,omitempty"`
	Cwd                  string                           `json:"cwd"`
	HookEventName        CurationHookRequestHookEventName `json:"hook_event_name"`
	SessionId            string                           `json:"session_id"`
	SourceWatermark      *int                             `json:"source_watermark,omitempty"`
	AdditionalProperties map[string]interface{}           `json:"-"`
}

// CurationHookRequestHookEventName defines model for CurationHookRequest.HookEventName.
type CurationHookRequestHookEventName string

// CurationHookResponse defines model for CurationHookResponse.
type CurationHookResponse struct {
	Accepted      bool                              `json:"accepted"`
	Enqueued      bool                              `json:"enqueued"`
	HookEventName CurationHookResponseHookEventName `json:"hook_event_name"`
	Recall        *RecallResult                     `json:"recall,omitempty"`
	Version       CurationHookResponseVersion       `json:"version"`
	WorkspaceId   *string                           `json:"workspace_id,omitempty"`
}

// CurationHookResponseHookEventName defines model for CurationHookResponse.HookEventName.
type CurationHookResponseHookEventName string

// CurationHookResponseVersion defines model for CurationHookResponse.Version.
type CurationHookResponseVersion string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      string               `json:"code"`
	Message   string               `json:"message"`
	ReceiptId openapi_types.UUID   `json:"receipt_id"`
	Retryable bool                 `json:"retryable"`
	Version   ErrorEnvelopeVersion `json:"version"`
}

// ErrorEnvelopeVersion defines model for ErrorEnvelope.Version.
type ErrorEnvelopeVersion string

// Explanation defines model for Explanation.
type Explanation struct {
	CreatedAt       time.Time                   `json:"created_at"`
	Lifecycle       ExplanationLifecycle        `json:"lifecycle"`
	MemoryId        openapi_types.UUID          `json:"memory_id"`
	Pinned          bool                        `json:"pinned"`
	ResolutionState *ExplanationResolutionState `json:"resolution_state,omitempty"`
	RevisionId      openapi_types.UUID          `json:"revision_id"`
	Trust           ExplanationTrust            `json:"trust"`
	UpdatedAt       time.Time                   `json:"updated_at"`
}

// ExplanationLifecycle defines model for Explanation.Lifecycle.
type ExplanationLifecycle string

// ExplanationResolutionState defines model for Explanation.ResolutionState.
type ExplanationResolutionState string

// ExplanationTrust defines model for Explanation.Trust.
type ExplanationTrust string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus  `json:"status"`
	Version HealthResponseVersion `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HealthResponseVersion defines model for HealthResponse.Version.
type HealthResponseVersion string

// MemoryItem defines model for MemoryItem.
type MemoryItem struct {
	Content         string                     `json:"content"`
	Kind            MemoryItemKind             `json:"kind"`
	Lifecycle       MemoryItemLifecycle        `json:"lifecycle"`
	MemoryId        openapi_types.UUID         `json:"memory_id"`
	ResolutionState *MemoryItemResolutionState `json:"resolution_state,omitempty"`
	RevisionId      openapi_types.UUID         `json:"revision_id"`
	Score           *float32                   `json:"score,omitempty"`
	Tags            []string                   `json:"tags"`
	Title           string                     `json:"title"`
	Trust           MemoryItemTrust            `json:"trust"`
	WorkspaceId     string                     `json:"workspace_id"`
}

// MemoryItemKind defines model for MemoryItem.Kind.
type MemoryItemKind string

// MemoryItemLifecycle defines model for MemoryItem.Lifecycle.
type MemoryItemLifecycle string

// MemoryItemResolutionState defines model for MemoryItem.ResolutionState.
type MemoryItemResolutionState string

// MemoryItemTrust defines model for MemoryItem.Trust.
type MemoryItemTrust string

// MemorySearchRequest defines model for MemorySearchRequest.
type MemorySearchRequest struct {
	Limit       *int   `json:"limit,omitempty"`
	Query       string `json:"query"`
	SessionId   string `json:"session_id"`
	WorkspaceId string `json:"workspace_id"`
}

// MemorySearchResponse defines model for MemorySearchResponse.
type MemorySearchResponse struct {
	Included  int                         `json:"included"`
	Items     []MemoryItem                `json:"items"`
	Omitted   int                         `json:"omitted"`
	ReceiptId openapi_types.UUID          `json:"receipt_id"`
	Version   MemorySearchResponseVersion `json:"version"`
}

// MemorySearchResponseVersion defines model for MemorySearchResponse.Version.
type MemorySearchResponseVersion string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Ready   bool                     `json:"ready"`
	Reason  *string                  `json:"reason,omitempty"`
	Version ReadinessResponseVersion `json:"version"`
}

// ReadinessResponseVersion defines model for ReadinessResponse.Version.
type ReadinessResponseVersion string

// RecallItem defines model for RecallItem.
type RecallItem struct {
	Content     string          `json:"content"`
	Kind        RecallItemKind  `json:"kind"`
	Label       string          `json:"label"`
	MemoryId    string          `json:"memory_id"`
	Pinned      bool            `json:"pinned"`
	RevisionId  string          `json:"revision_id"`
	Title       string          `json:"title"`
	Trust       RecallItemTrust `json:"trust"`
	WorkspaceId string          `json:"workspace_id"`
}

// RecallItemKind defines model for RecallItem.Kind.
type RecallItemKind string

// RecallItemTrust defines model for RecallItem.Trust.
type RecallItemTrust string

// RecallResult defines model for RecallResult.
type RecallResult struct {
	Context     string       `json:"context"`
	Included    int          `json:"included"`
	Items       []RecallItem `json:"items"`
	Omitted     int          `json:"omitted"`
	WorkspaceId string       `json:"workspace_id"`
}

// SessionStartHookSpecificOutput defines model for SessionStartHookSpecificOutput.
type SessionStartHookSpecificOutput struct {
	AdditionalContext string                                      `json:"additionalContext"`
	HookEventName     SessionStartHookSpecificOutputHookEventName `json:"hookEventName"`
}

// SessionStartHookSpecificOutputHookEventName defines model for SessionStartHookSpecificOutput.HookEventName.
type SessionStartHookSpecificOutputHookEventName string

// SessionStartRequest Raw Codex SessionStart event. Unknown fields are ignored and are never retained by the application.
type SessionStartRequest struct {
	Cwd                  string                           `json:"cwd"`
	HookEventName        SessionStartRequestHookEventName `json:"hook_event_name"`
	SessionId            string                           `json:"session_id"`
	AdditionalProperties map[string]interface{}           `json:"-"`
}

// SessionStartRequestHookEventName defines model for SessionStartRequest.HookEventName.
type SessionStartRequestHookEventName string

// SessionStartResponse defines model for SessionStartResponse.
type SessionStartResponse struct {
	HookSpecificOutput SessionStartHookSpecificOutput `json:"hookSpecificOutput"`
	Included           int                            `json:"included"`
	Items              []MemoryItem                   `json:"items"`
	NextCursor         *string                        `json:"next_cursor,omitempty"`
	Omitted            int                            `json:"omitted"`
	Version            SessionStartResponseVersion    `json:"version"`
	Warning            *string                        `json:"warning,omitempty"`
	WorkspaceId        string                         `json:"workspace_id"`
}

// SessionStartResponseVersion defines model for SessionStartResponse.Version.
type SessionStartResponseVersion string

// MemoryID defines model for MemoryID.
type MemoryID = openapi_types.UUID

// WorkspaceID defines model for WorkspaceID.
type WorkspaceID = string

// MemoryGetParams defines parameters for MemoryGet.
type MemoryGetParams struct {
	WorkspaceId WorkspaceID `form:"workspace_id" json:"workspace_id"`
}

// MemorySearchJSONRequestBody defines body for MemorySearch for application/json ContentType.
type MemorySearchJSONRequestBody = MemorySearchRequest

// PreCompactJSONRequestBody defines body for PreCompact for application/json ContentType.
type PreCompactJSONRequestBody = CurationHookRequest

// SessionEndJSONRequestBody defines body for SessionEnd for application/json ContentType.
type SessionEndJSONRequestBody = CurationHookRequest

// SessionStartJSONRequestBody defines body for SessionStart for application/json ContentType.
type SessionStartJSONRequestBody = SessionStartRequest

// UserPromptSubmitJSONRequestBody defines body for UserPromptSubmit for application/json ContentType.
type UserPromptSubmitJSONRequestBody = CurationHookRequest

// Getter for additional properties for CurationHookRequest. Returns the specified
// element and whether it was found
func (a CurationHookRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CurationHookRequest
func (a *CurationHookRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CurationHookRequest to handle AdditionalProperties
func (a *CurationHookRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["current_prompt"]; found {
		err = json.Unmarshal(raw, &a.CurrentPrompt)
		if err != nil {
			return fmt.Errorf("error reading 'current_prompt': %w", err)
		}
		delete(object, "current_prompt")
	}

	if raw, found := object["cwd"]; found {
		err = json.Unmarshal(raw, &a.Cwd)
		if err != nil {
			return fmt.Errorf("error reading 'cwd': %w", err)
		}
		delete(object, "cwd")
	}

	if raw, found := object["hook_event_name"]; found {
		err = json.Unmarshal(raw, &a.HookEventName)
		if err != nil {
			return fmt.Errorf("error reading 'hook_event_name': %w", err)
		}
		delete(object, "hook_event_name")
	}

	if raw, found := object["session_id"]; found {
		err = json.Unmarshal(raw, &a.SessionId)
		if err != nil {
			return fmt.Errorf("error reading 'session_id': %w", err)
		}
		delete(object, "session_id")
	}

	if raw, found := object["source_watermark"]; found {
		err = json.Unmarshal(raw, &a.SourceWatermark)
		if err != nil {
			return fmt.Errorf("error reading 'source_watermark': %w", err)
		}
		delete(object, "source_watermark")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CurationHookRequest to handle AdditionalProperties
func (a CurationHookRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CurrentPrompt != nil {
		object["current_prompt"], err = json.Marshal(a.CurrentPrompt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'current_prompt': %w", err)
		}
	}

	object["cwd"], err = json.Marshal(a.Cwd)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cwd': %w", err)
	}

	object["hook_event_name"], err = json.Marshal(a.HookEventName)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'hook_event_name': %w", err)
	}

	object["session_id"], err = json.Marshal(a.SessionId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'session_id': %w", err)
	}

	if a.SourceWatermark != nil {
		object["source_watermark"], err = json.Marshal(a.SourceWatermark)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'source_watermark': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SessionStartRequest. Returns the specified
// element and whether it was found
func (a SessionStartRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionStartRequest
func (a *SessionStartRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionStartRequest to handle AdditionalProperties
func (a *SessionStartRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cwd"]; found {
		err = json.Unmarshal(raw, &a.Cwd)
		if err != nil {
			return fmt.Errorf("error reading 'cwd': %w", err)
		}
		delete(object, "cwd")
	}

	if raw, found := object["hook_event_name"]; found {
		err = json.Unmarshal(raw, &a.HookEventName)
		if err != nil {
			return fmt.Errorf("error reading 'hook_event_name': %w", err)
		}
		delete(object, "hook_event_name")
	}

	if raw, found := object["session_id"]; found {
		err = json.Unmarshal(raw, &a.SessionId)
		if err != nil {
			return fmt.Errorf("error reading 'session_id': %w", err)
		}
		delete(object, "session_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionStartRequest to handle AdditionalProperties
func (a SessionStartRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["cwd"], err = json.Marshal(a.Cwd)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cwd': %w", err)
	}

	object["hook_event_name"], err = json.Marshal(a.HookEventName)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'hook_event_name': %w", err)
	}

	object["session_id"], err = json.Marshal(a.SessionId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'session_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpbc9u4Ff4rGLSP1M12kl29JWnaZGbT9djd9sHj8UDgkYSIBOgDQLbq0X/vACBFUoKuvmw73TdJBIFz",
	"vu9cPgB6olzlhZIgjabDJ1owZDkYQP/tO+QKF9/+4j4LSYe0YGZKEypZDnRIc//4TqQ0oQj3ViCkdGjQ",
	"QkI1n0LO3ItjhTkzdEit9SPNonAva4NCTuhymdB/KZzpgnForHRvARf1Ug/VkH2r5ezxF5ATM6XDs3fv",
	"E5oLWX0fbK69rF717n62yIxQ8qtSsyu4t6CN+5mlqXA/s+wSVQFoBOhq4aLxyxPlFhGkuStQ5YVZM+f8",
	"7MP7nzZMSCh/SNdGXvR/3md5QqdKze5g7pYLGD1RkDanwxv6mwa89CZc21EuDE3oJcJnlReMuy/XoLVQ",
	"8otM6W1kZh0eO6SPBTShWlnkcPfADGDOcOanEFLkzrT+6gUhDUwAPf01mTfNtTddDFjVJqvRD+DGrdpm",
	"ThdKathO3ZhleoM7xjkUBrzP5fwjpTJg0i0A8t6C3fb09bhA4CzL3IR/RhjTIf1Tr07YXhm7vSs/6gq0",
	"zTwcc0A3qQ9JJV0UU8MyhoJ1eYlUx9ncnQ9oZNFWstUONzK2SVm1WIyvFagNBGP8fUFU+EXOIVPFscRx",
	"lUIZZbsCMwet2eSQkQgcRGFK5/eULzfc4IKNMojHxg4uwHkd5WArxN7Z2pmWsU1ToiA/FhmTnv1jIUZg",
	"BtI7ZlqIpMxAxwjP9AYsmRgDX/CslQ2MGzF3w+8tQyaNkD42xgonyhhwHhYWJxBPhrrfHMJLIaTclrAI",
	"WmXWeX+nDTMtG1Xh7fBD5rAtLeeiUSP32mLQhl5SLTIHFGPhnbdy9SW2lC3SI7FfC552l67trqxqUrVC",
	"LWly3jIiFllfgWVmemLhdQRY3cwPNYthuCORpn79QzKpXKyeLeZOKXsM5EeXImlArjf+nwY/n0X8mQmZ",
	"NkMiBKKfkkNq0X0eM5GFT9owmQo5uRNSG7TctI0/LO+en1RvnTiaK2wWVmnzkZMNCTVs4jEXBnK9hvj7",
	"i5ij7PFbGHtW6xCGyBZ+OmECZOt654hcvn12L92eq2sC2AdPZXWyCrwSllhqbw/0a2DIp3sFbzTiM+E0",
	"zfCJpjBmTn0MB30PdRB8DumV+htsqr+k1Plt3Af9s4v9QvM5KnWdleN2DW3Oqp3KGkMN+/ZDf1LhFJJn",
	"Ng0tbpfETuocWX3YpSYb5W9v2qhcGHOICUeKqh3FPuRIR3vojlNPwf2kRq52oGVhjLArYKmQoPWJbCGw",
	"dLFNjTAdfD0GBz/hIf6HlXe3vLCD+F9teWwEWRS+VnM7UiG2GtVmF3iBfpHQCUhAp6x+j95RtoiV4gsw",
	"bjaV7fFS7jhPiJjHAyOmVeOqrnKevGi9a8R+q96dP6PcHUfdGkE7y1QFX4yV8jDh2jA0X5WaXRfAxVjw",
	"X60p7LE81UM/Nxjbfyj1ZQ7S/L08BqmKVtOyvQWrPUsSsWSf8wee3qWgOYoi7IjpFXsgn1UKj6Q5FfEH",
	"Gl3ym5xJ9SDJWECWasIQiJhIhZASJlP/XcIckCAY5va1ZLQgZgqEFUUmuN92d+lGMmwc/r0bnJ1y9ncY",
	"0M+STS9zVNem6aRWOo2G9q4U35MY64XmdxJTEh7NHbeoFUZ7zsHVZ4dqKFnraAfFtvM/htJ9jNlw6tng",
	"MSUuwu9mJPlY5haFWVw7rENojIAh4EfrIrj69tdKbKqC3VuvLPwLruH7ATUGU2OKcC0g5FiFfU2zRLiJ",
	"QRqXzpAmJFOqGDE+6yiZLYirzKgyoi2OGQcyVugLQKY4y0hozyRlkIdCUCoI+o/ATOc75OXQaqKPl98a",
	"sm1I+91+98wHQgGSFYIO6Xl30O27qsLM1APQK1/uzQe9sGQvKGV/u6NCTXTJ5AvSt5QOW1uR8m4FtPmk",
	"glxtCLxGJev9KBVrffOyPwvaG81lO1hcRQ4HDL4keGfO+v1XMqGsO96GNsX/LNVZQjRnUgJ2Jo5sElAk",
	"6CWP7joaLl7QvPYJeMwulonUz0xKidx1w5ZJjPKnlRhcuoUnsJX2v4HXgI1rv5u4ofWQ3upacJnsHdu8",
	"21vevjq/odBuoverBDLfwmzAqmT04u0YDRYTqQwZKytTIqSvF2UCupjjqjiQ5h48FhkTcg/dX8pRp1P+",
	"mhw2bygigF2zMRBkcibkxIuu1ekWycGwlBkWA6tA6PDywm1rEWxdyr1GCYxdLr9xCYzekkZw/qgXkk9R",
	"SWU1aaDnak91f0gYd3o4g3QCuRPIEeArrQFh1x8HvnEB+gfwTeAb6J2Euld4e3GvNgqvgXxsR/bGyEd3",
	"GxHkP7kCDOmqR5Bym000ZMDD3u2/ouM7GwZvZ0ND8G7YMTh/OzvK8CEjlS4IPHKAVPtmWd47ECWBfBef",
	"iL+Q8Pa967+hfdeAc8GBCE2sZHMmMjbKgCistAbxZ53uuZBugQxMtLNbDdgJ/x/q6PCPka0pHPlvyf95",
	"Aa3SOABIwr9nwvlMs7TuLafhQvnfW8XU1/L5K7q8dqcecfYSFQetXUyxTMx9ONWbYjq8ufW++OP/7a5c",
	"hcev6MnmzUksgYxCNoGVNk88awWqH6H8+gO2cOXx0sl9kH3rYJORNV66VzaFyGmg3z6MuLl1ylkDzivF",
	"3Z7/F2EAWbY6UiBKZguaUItZeS4x7PUGZx+6/W6/Oxh+uDj/QJe3y/8EAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
