// Code generated by cmd/codexrpcgen; DO NOT EDIT.

package protocol

import (
	"context"

	"github.com/sourcegraph/jsonrpc2"
)

type Client struct {
	conn *jsonrpc2.Conn
}

func NewClient(conn *jsonrpc2.Conn) *Client { return &Client{conn: conn} }

func (client *Client) Initialize(ctx context.Context, params InitializeParams) (InitializeResponse, error) {
	var result InitializeResponse
	if err := client.conn.Call(ctx, "initialize", params, &result); err != nil {
		return InitializeResponse{}, err
	}
	return result, nil
}

func (client *Client) ModelList(ctx context.Context, params ModelListParams) (ModelListResponse, error) {
	var result ModelListResponse
	if err := client.conn.Call(ctx, "model/list", params, &result); err != nil {
		return ModelListResponse{}, err
	}
	return result, nil
}

func (client *Client) ThreadFork(ctx context.Context, params ThreadForkParams) (ThreadForkResponse, error) {
	var result ThreadForkResponse
	if err := client.conn.Call(ctx, "thread/fork", params, &result); err != nil {
		return ThreadForkResponse{}, err
	}
	return result, nil
}

func (client *Client) ThreadRead(ctx context.Context, params ThreadReadParams) (ThreadReadResponse, error) {
	var result ThreadReadResponse
	if err := client.conn.Call(ctx, "thread/read", params, &result); err != nil {
		return ThreadReadResponse{}, err
	}
	return result, nil
}

func (client *Client) ThreadStart(ctx context.Context, params ThreadStartParams) (ThreadStartResponse, error) {
	var result ThreadStartResponse
	if err := client.conn.Call(ctx, "thread/start", params, &result); err != nil {
		return ThreadStartResponse{}, err
	}
	return result, nil
}

func (client *Client) TurnStart(ctx context.Context, params TurnStartParams) (TurnStartResponse, error) {
	var result TurnStartResponse
	if err := client.conn.Call(ctx, "turn/start", params, &result); err != nil {
		return TurnStartResponse{}, err
	}
	return result, nil
}
