// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

type ClientInfo struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Title corresponds to the JSON schema field "title".
	Title interface{} `json:"title,omitempty,omitzero" yaml:"title,omitempty" mapstructure:"title,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version interface{} `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

type ClientInfoTitle_0 *string

type ClientInfoVersion_0 *string

type CuratedProtocol struct {
	// InitializeParams corresponds to the JSON schema field "initializeParams".
	InitializeParams *InitializeParams `json:"initializeParams,omitempty,omitzero" yaml:"initializeParams,omitempty" mapstructure:"initializeParams,omitempty"`

	// InitializeResult corresponds to the JSON schema field "initializeResult".
	InitializeResult *InitializeResponse `json:"initializeResult,omitempty,omitzero" yaml:"initializeResult,omitempty" mapstructure:"initializeResult,omitempty"`

	// ModelListParams corresponds to the JSON schema field "model_listParams".
	ModelListParams *ModelListParams `json:"model_listParams,omitempty,omitzero" yaml:"model_listParams,omitempty" mapstructure:"model_listParams,omitempty"`

	// ModelListResult corresponds to the JSON schema field "model_listResult".
	ModelListResult *ModelListResponse `json:"model_listResult,omitempty,omitzero" yaml:"model_listResult,omitempty" mapstructure:"model_listResult,omitempty"`

	// ThreadForkParams corresponds to the JSON schema field "thread_forkParams".
	ThreadForkParams *ThreadForkParams `json:"thread_forkParams,omitempty,omitzero" yaml:"thread_forkParams,omitempty" mapstructure:"thread_forkParams,omitempty"`

	// ThreadForkResult corresponds to the JSON schema field "thread_forkResult".
	ThreadForkResult *ThreadForkResponse `json:"thread_forkResult,omitempty,omitzero" yaml:"thread_forkResult,omitempty" mapstructure:"thread_forkResult,omitempty"`

	// ThreadReadParams corresponds to the JSON schema field "thread_readParams".
	ThreadReadParams *ThreadReadParams `json:"thread_readParams,omitempty,omitzero" yaml:"thread_readParams,omitempty" mapstructure:"thread_readParams,omitempty"`

	// ThreadReadResult corresponds to the JSON schema field "thread_readResult".
	ThreadReadResult *ThreadReadResponse `json:"thread_readResult,omitempty,omitzero" yaml:"thread_readResult,omitempty" mapstructure:"thread_readResult,omitempty"`

	// ThreadStartParams corresponds to the JSON schema field "thread_startParams".
	ThreadStartParams *ThreadStartParams `json:"thread_startParams,omitempty,omitzero" yaml:"thread_startParams,omitempty" mapstructure:"thread_startParams,omitempty"`

	// ThreadStartResult corresponds to the JSON schema field "thread_startResult".
	ThreadStartResult *ThreadStartResponse `json:"thread_startResult,omitempty,omitzero" yaml:"thread_startResult,omitempty" mapstructure:"thread_startResult,omitempty"`

	// TurnStartParams corresponds to the JSON schema field "turn_startParams".
	TurnStartParams *TurnStartParams `json:"turn_startParams,omitempty,omitzero" yaml:"turn_startParams,omitempty" mapstructure:"turn_startParams,omitempty"`

	// TurnStartResult corresponds to the JSON schema field "turn_startResult".
	TurnStartResult *TurnStartResponse `json:"turn_startResult,omitempty,omitzero" yaml:"turn_startResult,omitempty" mapstructure:"turn_startResult,omitempty"`
}

type InitializeCapabilities struct {
	// ExperimentalApi corresponds to the JSON schema field "experimentalApi".
	ExperimentalApi interface{} `json:"experimentalApi,omitempty,omitzero" yaml:"experimentalApi,omitempty" mapstructure:"experimentalApi,omitempty"`
}

type InitializeCapabilitiesExperimentalApi_0 *bool

type InitializeParams struct {
	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities *InitializeCapabilities `json:"capabilities,omitempty,omitzero" yaml:"capabilities,omitempty" mapstructure:"capabilities,omitempty"`

	// ClientInfo corresponds to the JSON schema field "clientInfo".
	ClientInfo ClientInfo `json:"clientInfo" yaml:"clientInfo" mapstructure:"clientInfo"`
}

type InitializeResponse struct {
	// CodexHome corresponds to the JSON schema field "codexHome".
	CodexHome string `json:"codexHome" yaml:"codexHome" mapstructure:"codexHome"`

	// PlatformFamily corresponds to the JSON schema field "platformFamily".
	PlatformFamily string `json:"platformFamily" yaml:"platformFamily" mapstructure:"platformFamily"`

	// PlatformOs corresponds to the JSON schema field "platformOs".
	PlatformOs string `json:"platformOs" yaml:"platformOs" mapstructure:"platformOs"`

	// UserAgent corresponds to the JSON schema field "userAgent".
	UserAgent string `json:"userAgent" yaml:"userAgent" mapstructure:"userAgent"`
}

type Model struct {
	// DisplayName corresponds to the JSON schema field "displayName".
	DisplayName string `json:"displayName" yaml:"displayName" mapstructure:"displayName"`

	// Hidden corresponds to the JSON schema field "hidden".
	Hidden *bool `json:"hidden,omitempty,omitzero" yaml:"hidden,omitempty" mapstructure:"hidden,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// IsDefault corresponds to the JSON schema field "isDefault".
	IsDefault *bool `json:"isDefault,omitempty,omitzero" yaml:"isDefault,omitempty" mapstructure:"isDefault,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model" yaml:"model" mapstructure:"model"`

	// SupportedReasoningEfforts corresponds to the JSON schema field
	// "supportedReasoningEfforts".
	SupportedReasoningEfforts []ReasoningEffortOption `json:"supportedReasoningEfforts,omitempty,omitzero" yaml:"supportedReasoningEfforts,omitempty" mapstructure:"supportedReasoningEfforts,omitempty"`
}

type ModelListParams struct {
	// Cursor corresponds to the JSON schema field "cursor".
	Cursor interface{} `json:"cursor,omitempty,omitzero" yaml:"cursor,omitempty" mapstructure:"cursor,omitempty"`

	// IncludeHidden corresponds to the JSON schema field "includeHidden".
	IncludeHidden interface{} `json:"includeHidden,omitempty,omitzero" yaml:"includeHidden,omitempty" mapstructure:"includeHidden,omitempty"`

	// Limit corresponds to the JSON schema field "limit".
	Limit interface{} `json:"limit,omitempty,omitzero" yaml:"limit,omitempty" mapstructure:"limit,omitempty"`
}

type ModelListParamsCursor_0 *string

type ModelListParamsIncludeHidden_0 *bool

type ModelListParamsLimit_0 *int

type ModelListResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data []Model `json:"data" yaml:"data" mapstructure:"data"`

	// NextCursor corresponds to the JSON schema field "nextCursor".
	NextCursor interface{} `json:"nextCursor,omitempty,omitzero" yaml:"nextCursor,omitempty" mapstructure:"nextCursor,omitempty"`
}

type ModelListResponseNextCursor_0 *string

type ReasoningEffortOption struct {
	// ReasoningEffort corresponds to the JSON schema field "reasoningEffort".
	ReasoningEffort string `json:"reasoningEffort" yaml:"reasoningEffort" mapstructure:"reasoningEffort"`
}

type ThreadForkParams struct {
	// ApprovalPolicy corresponds to the JSON schema field "approvalPolicy".
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty,omitzero" yaml:"approvalPolicy,omitempty" mapstructure:"approvalPolicy,omitempty"`

	// BaseInstructions corresponds to the JSON schema field "baseInstructions".
	BaseInstructions interface{} `json:"baseInstructions,omitempty,omitzero" yaml:"baseInstructions,omitempty" mapstructure:"baseInstructions,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *ThreadForkParamsConfig `json:"config,omitempty,omitzero" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd interface{} `json:"cwd,omitempty,omitzero" yaml:"cwd,omitempty" mapstructure:"cwd,omitempty"`

	// DeveloperInstructions corresponds to the JSON schema field
	// "developerInstructions".
	DeveloperInstructions interface{} `json:"developerInstructions,omitempty,omitzero" yaml:"developerInstructions,omitempty" mapstructure:"developerInstructions,omitempty"`

	// Ephemeral corresponds to the JSON schema field "ephemeral".
	Ephemeral interface{} `json:"ephemeral,omitempty,omitzero" yaml:"ephemeral,omitempty" mapstructure:"ephemeral,omitempty"`

	// LastTurnID corresponds to the JSON schema field "lastTurnId".
	LastTurnID interface{} `json:"lastTurnId,omitempty,omitzero" yaml:"lastTurnId,omitempty" mapstructure:"lastTurnId,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model interface{} `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// ModelProvider corresponds to the JSON schema field "modelProvider".
	ModelProvider interface{} `json:"modelProvider,omitempty,omitzero" yaml:"modelProvider,omitempty" mapstructure:"modelProvider,omitempty"`

	// Sandbox corresponds to the JSON schema field "sandbox".
	Sandbox interface{} `json:"sandbox,omitempty,omitzero" yaml:"sandbox,omitempty" mapstructure:"sandbox,omitempty"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId" yaml:"threadId" mapstructure:"threadId"`
}

type ThreadForkParamsApprovalPolicy_0 *string

type ThreadForkParamsBaseInstructions_0 *string

type ThreadForkParamsConfig map[string]interface{}

type ThreadForkParamsConfig_0 map[string]interface{}

type ThreadForkParamsCwd_0 *string

type ThreadForkParamsDeveloperInstructions_0 *string

type ThreadForkParamsEphemeral_0 *bool

type ThreadForkParamsLastTurnID_0 *string

type ThreadForkParamsModelProvider_0 *string

type ThreadForkParamsModel_0 *string

type ThreadForkParamsSandbox_0 *string

type ThreadForkResponse struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd interface{} `json:"cwd,omitempty,omitzero" yaml:"cwd,omitempty" mapstructure:"cwd,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model interface{} `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// ReasoningEffort corresponds to the JSON schema field "reasoningEffort".
	ReasoningEffort interface{} `json:"reasoningEffort,omitempty,omitzero" yaml:"reasoningEffort,omitempty" mapstructure:"reasoningEffort,omitempty"`

	// Thread corresponds to the JSON schema field "thread".
	Thread ThreadSnapshot `json:"thread" yaml:"thread" mapstructure:"thread"`
}

type ThreadForkResponseCwd_0 *string

type ThreadForkResponseModel_0 *string

type ThreadForkResponseReasoningEffort_0 *string

type ThreadItem struct {
	// Content corresponds to the JSON schema field "content".
	Content interface{} `json:"content,omitempty,omitzero" yaml:"content,omitempty" mapstructure:"content,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message interface{} `json:"message,omitempty,omitzero" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name interface{} `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status interface{} `json:"status,omitempty,omitzero" yaml:"status,omitempty" mapstructure:"status,omitempty"`

	// Text corresponds to the JSON schema field "text".
	Text interface{} `json:"text,omitempty,omitzero" yaml:"text,omitempty" mapstructure:"text,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type ThreadItemContent_0 *string

type ThreadItemMessage_0 *string

type ThreadItemName_0 *string

type ThreadItemStatus_0 *string

type ThreadItemText_0 *string

type ThreadReadParams struct {
	// IncludeTurns corresponds to the JSON schema field "includeTurns".
	IncludeTurns interface{} `json:"includeTurns,omitempty,omitzero" yaml:"includeTurns,omitempty" mapstructure:"includeTurns,omitempty"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId" yaml:"threadId" mapstructure:"threadId"`
}

type ThreadReadParamsIncludeTurns_0 *bool

type ThreadReadResponse struct {
	// Thread corresponds to the JSON schema field "thread".
	Thread ThreadSnapshot `json:"thread" yaml:"thread" mapstructure:"thread"`
}

type ThreadSnapshot struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd interface{} `json:"cwd,omitempty,omitzero" yaml:"cwd,omitempty" mapstructure:"cwd,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Items corresponds to the JSON schema field "items".
	Items []ThreadItem `json:"items,omitempty,omitzero" yaml:"items,omitempty" mapstructure:"items,omitempty"`

	// Turns corresponds to the JSON schema field "turns".
	Turns []Turn `json:"turns,omitempty,omitzero" yaml:"turns,omitempty" mapstructure:"turns,omitempty"`
}

type ThreadSnapshotCwd_0 *string

type ThreadStartParams struct {
	// ApprovalPolicy corresponds to the JSON schema field "approvalPolicy".
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty,omitzero" yaml:"approvalPolicy,omitempty" mapstructure:"approvalPolicy,omitempty"`

	// BaseInstructions corresponds to the JSON schema field "baseInstructions".
	BaseInstructions interface{} `json:"baseInstructions,omitempty,omitzero" yaml:"baseInstructions,omitempty" mapstructure:"baseInstructions,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *ThreadStartParamsConfig `json:"config,omitempty,omitzero" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd interface{} `json:"cwd,omitempty,omitzero" yaml:"cwd,omitempty" mapstructure:"cwd,omitempty"`

	// DeveloperInstructions corresponds to the JSON schema field
	// "developerInstructions".
	DeveloperInstructions interface{} `json:"developerInstructions,omitempty,omitzero" yaml:"developerInstructions,omitempty" mapstructure:"developerInstructions,omitempty"`

	// Ephemeral corresponds to the JSON schema field "ephemeral".
	Ephemeral interface{} `json:"ephemeral,omitempty,omitzero" yaml:"ephemeral,omitempty" mapstructure:"ephemeral,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model interface{} `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// ModelProvider corresponds to the JSON schema field "modelProvider".
	ModelProvider interface{} `json:"modelProvider,omitempty,omitzero" yaml:"modelProvider,omitempty" mapstructure:"modelProvider,omitempty"`

	// Sandbox corresponds to the JSON schema field "sandbox".
	Sandbox interface{} `json:"sandbox,omitempty,omitzero" yaml:"sandbox,omitempty" mapstructure:"sandbox,omitempty"`
}

type ThreadStartParamsApprovalPolicy_0 *string

type ThreadStartParamsBaseInstructions_0 *string

type ThreadStartParamsConfig map[string]interface{}

type ThreadStartParamsConfig_0 map[string]interface{}

type ThreadStartParamsCwd_0 *string

type ThreadStartParamsDeveloperInstructions_0 *string

type ThreadStartParamsEphemeral_0 *bool

type ThreadStartParamsModelProvider_0 *string

type ThreadStartParamsModel_0 *string

type ThreadStartParamsSandbox_0 *string

type ThreadStartResponse struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd interface{} `json:"cwd,omitempty,omitzero" yaml:"cwd,omitempty" mapstructure:"cwd,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model interface{} `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// ReasoningEffort corresponds to the JSON schema field "reasoningEffort".
	ReasoningEffort interface{} `json:"reasoningEffort,omitempty,omitzero" yaml:"reasoningEffort,omitempty" mapstructure:"reasoningEffort,omitempty"`

	// Thread corresponds to the JSON schema field "thread".
	Thread ThreadSnapshot `json:"thread" yaml:"thread" mapstructure:"thread"`
}

type ThreadStartResponseCwd_0 *string

type ThreadStartResponseModel_0 *string

type ThreadStartResponseReasoningEffort_0 *string

type Turn struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Items corresponds to the JSON schema field "items".
	Items []ThreadItem `json:"items,omitempty,omitzero" yaml:"items,omitempty" mapstructure:"items,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status interface{} `json:"status,omitempty,omitzero" yaml:"status,omitempty" mapstructure:"status,omitempty"`
}

type TurnStartParams struct {
	// ApprovalPolicy corresponds to the JSON schema field "approvalPolicy".
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty,omitzero" yaml:"approvalPolicy,omitempty" mapstructure:"approvalPolicy,omitempty"`

	// Cwd corresponds to the JSON schema field "cwd".
	Cwd interface{} `json:"cwd,omitempty,omitzero" yaml:"cwd,omitempty" mapstructure:"cwd,omitempty"`

	// Effort corresponds to the JSON schema field "effort".
	Effort interface{} `json:"effort,omitempty,omitzero" yaml:"effort,omitempty" mapstructure:"effort,omitempty"`

	// Input corresponds to the JSON schema field "input".
	Input []UserInput `json:"input" yaml:"input" mapstructure:"input"`

	// Model corresponds to the JSON schema field "model".
	Model interface{} `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// OutputSchema corresponds to the JSON schema field "outputSchema".
	OutputSchema *TurnStartParamsOutputSchema `json:"outputSchema,omitempty,omitzero" yaml:"outputSchema,omitempty" mapstructure:"outputSchema,omitempty"`

	// SandboxPolicy corresponds to the JSON schema field "sandboxPolicy".
	SandboxPolicy *TurnStartParamsSandboxPolicy `json:"sandboxPolicy,omitempty,omitzero" yaml:"sandboxPolicy,omitempty" mapstructure:"sandboxPolicy,omitempty"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId" yaml:"threadId" mapstructure:"threadId"`
}

type TurnStartParamsApprovalPolicy_0 *string

type TurnStartParamsCwd_0 *string

type TurnStartParamsEffort_0 *string

type TurnStartParamsModel_0 *string

type TurnStartParamsOutputSchema map[string]interface{}

type TurnStartParamsOutputSchema_0 map[string]interface{}

type TurnStartParamsSandboxPolicy map[string]interface{}

type TurnStartParamsSandboxPolicy_0 map[string]interface{}

type TurnStartResponse struct {
	// Turn corresponds to the JSON schema field "turn".
	Turn Turn `json:"turn" yaml:"turn" mapstructure:"turn"`
}

type TurnStatus_0 *string

type UserInput struct {
	// Text corresponds to the JSON schema field "text".
	Text interface{} `json:"text,omitempty,omitzero" yaml:"text,omitempty" mapstructure:"text,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type UserInputText_0 *string
