// Code generated by cmd/codexrpcgen; DO NOT EDIT.

package protocol

import "encoding/json"

const (
	NotificationTurnStarted      = "turn/started"
	NotificationAgentMessageDone = "item/completed"
	NotificationTurnCompleted    = "turn/completed"
	NotificationError            = "error"
)

type Notification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params"`
}

func (notification Notification) IsCompletion() bool {
	return notification.Method == NotificationAgentMessageDone || notification.Method == NotificationTurnCompleted
}
