// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: curation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const claimCurationJob = `-- name: ClaimCurationJob :execrows
UPDATE curation_jobs
SET state = 'running', attempt_count = attempt_count + 1,
    next_attempt_at = NULL, updated_at = ?
WHERE id = ? AND state IN ('pending', 'retry_wait')
  AND (next_attempt_at IS NULL OR next_attempt_at <= ?)
  AND expires_at > ?
`

type ClaimCurationJobParams struct {
	UpdatedAt     string         `json:"updated_at"`
	ID            string         `json:"id"`
	NextAttemptAt sql.NullString `json:"next_attempt_at"`
	ExpiresAt     string         `json:"expires_at"`
}

func (q *Queries) ClaimCurationJob(ctx context.Context, arg ClaimCurationJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimCurationJob,
		arg.UpdatedAt,
		arg.ID,
		arg.NextAttemptAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCurationSessionCounter = `-- name: DeleteCurationSessionCounter :exec
DELETE FROM curation_session_counters WHERE session_digest = ?
`

func (q *Queries) DeleteCurationSessionCounter(ctx context.Context, sessionDigest []byte) error {
	_, err := q.db.ExecContext(ctx, deleteCurationSessionCounter, sessionDigest)
	return err
}

const finishCurationJob = `-- name: FinishCurationJob :execrows
UPDATE curation_jobs
SET state = ?, thread_locator_ciphertext = X'', snapshot_ciphertext = X'',
    next_attempt_at = NULL, safe_error_class = ?, updated_at = ?
WHERE id = ? AND state = 'running'
`

type FinishCurationJobParams struct {
	State          string `json:"state"`
	SafeErrorClass string `json:"safe_error_class"`
	UpdatedAt      string `json:"updated_at"`
	ID             string `json:"id"`
}

func (q *Queries) FinishCurationJob(ctx context.Context, arg FinishCurationJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishCurationJob,
		arg.State,
		arg.SafeErrorClass,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incrementCurationSessionCounter = `-- name: IncrementCurationSessionCounter :exec
INSERT INTO curation_session_counters(session_digest, prompt_count, last_watermark, expires_at)
VALUES (?, 1, ?, ?)
ON CONFLICT(session_digest) DO UPDATE SET
    prompt_count = curation_session_counters.prompt_count + 1,
    last_watermark = max(curation_session_counters.last_watermark, excluded.last_watermark),
    expires_at = max(curation_session_counters.expires_at, excluded.expires_at)
`

type IncrementCurationSessionCounterParams struct {
	SessionDigest []byte `json:"session_digest"`
	LastWatermark int64  `json:"last_watermark"`
	ExpiresAt     string `json:"expires_at"`
}

func (q *Queries) IncrementCurationSessionCounter(ctx context.Context, arg IncrementCurationSessionCounterParams) error {
	_, err := q.db.ExecContext(ctx, incrementCurationSessionCounter, arg.SessionDigest, arg.LastWatermark, arg.ExpiresAt)
	return err
}

const insertCurationJob = `-- name: InsertCurationJob :exec
INSERT INTO curation_jobs(
    id, workspace_id, reason, reason_flags, priority, session_digest,
    source_watermark, thread_locator_ciphertext, snapshot_ciphertext,
    state, attempt_count, next_attempt_at, expires_at, provider_name,
    safe_error_class, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCurationJobParams struct {
	ID                      string         `json:"id"`
	WorkspaceID             string         `json:"workspace_id"`
	Reason                  string         `json:"reason"`
	ReasonFlags             string         `json:"reason_flags"`
	Priority                int64          `json:"priority"`
	SessionDigest           []byte         `json:"session_digest"`
	SourceWatermark         int64          `json:"source_watermark"`
	ThreadLocatorCiphertext []byte         `json:"thread_locator_ciphertext"`
	SnapshotCiphertext      []byte         `json:"snapshot_ciphertext"`
	State                   string         `json:"state"`
	AttemptCount            int64          `json:"attempt_count"`
	NextAttemptAt           sql.NullString `json:"next_attempt_at"`
	ExpiresAt               string         `json:"expires_at"`
	ProviderName            string         `json:"provider_name"`
	SafeErrorClass          string         `json:"safe_error_class"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

func (q *Queries) InsertCurationJob(ctx context.Context, arg InsertCurationJobParams) error {
	_, err := q.db.ExecContext(ctx, insertCurationJob,
		arg.ID,
		arg.WorkspaceID,
		arg.Reason,
		arg.ReasonFlags,
		arg.Priority,
		arg.SessionDigest,
		arg.SourceWatermark,
		arg.ThreadLocatorCiphertext,
		arg.SnapshotCiphertext,
		arg.State,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.ExpiresAt,
		arg.ProviderName,
		arg.SafeErrorClass,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const purgeExpiredCurationJobs = `-- name: PurgeExpiredCurationJobs :execrows
DELETE FROM curation_jobs
WHERE expires_at <= ? AND state <> 'running'
`

func (q *Queries) PurgeExpiredCurationJobs(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredCurationJobs, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const readClaimableCurationJob = `-- name: ReadClaimableCurationJob :one
SELECT id, workspace_id, reason, reason_flags, priority, session_digest,
       source_watermark, thread_locator_ciphertext, snapshot_ciphertext,
       state, attempt_count, next_attempt_at, expires_at, provider_name,
       safe_error_class, created_at, updated_at
FROM curation_jobs
WHERE state IN ('pending', 'retry_wait')
  AND (next_attempt_at IS NULL OR next_attempt_at <= ?)
  AND expires_at > ?
ORDER BY priority DESC, created_at ASC, id ASC
LIMIT 1
`

type ReadClaimableCurationJobParams struct {
	NextAttemptAt sql.NullString `json:"next_attempt_at"`
	ExpiresAt     string         `json:"expires_at"`
}

type ReadClaimableCurationJobRow struct {
	ID                      string         `json:"id"`
	WorkspaceID             string         `json:"workspace_id"`
	Reason                  string         `json:"reason"`
	ReasonFlags             string         `json:"reason_flags"`
	Priority                int64          `json:"priority"`
	SessionDigest           []byte         `json:"session_digest"`
	SourceWatermark         int64          `json:"source_watermark"`
	ThreadLocatorCiphertext []byte         `json:"thread_locator_ciphertext"`
	SnapshotCiphertext      []byte         `json:"snapshot_ciphertext"`
	State                   string         `json:"state"`
	AttemptCount            int64          `json:"attempt_count"`
	NextAttemptAt           sql.NullString `json:"next_attempt_at"`
	ExpiresAt               string         `json:"expires_at"`
	ProviderName            string         `json:"provider_name"`
	SafeErrorClass          string         `json:"safe_error_class"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

func (q *Queries) ReadClaimableCurationJob(ctx context.Context, arg ReadClaimableCurationJobParams) (ReadClaimableCurationJobRow, error) {
	row := q.db.QueryRowContext(ctx, readClaimableCurationJob, arg.NextAttemptAt, arg.ExpiresAt)
	var i ReadClaimableCurationJobRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Reason,
		&i.ReasonFlags,
		&i.Priority,
		&i.SessionDigest,
		&i.SourceWatermark,
		&i.ThreadLocatorCiphertext,
		&i.SnapshotCiphertext,
		&i.State,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ExpiresAt,
		&i.ProviderName,
		&i.SafeErrorClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readCurationJobByDigestWatermark = `-- name: ReadCurationJobByDigestWatermark :one
SELECT id, workspace_id, reason, reason_flags, priority, session_digest,
       source_watermark, thread_locator_ciphertext, snapshot_ciphertext,
       state, attempt_count, next_attempt_at, expires_at, provider_name,
       safe_error_class, created_at, updated_at
FROM curation_jobs
WHERE session_digest = ? AND source_watermark = ?
`

type ReadCurationJobByDigestWatermarkParams struct {
	SessionDigest   []byte `json:"session_digest"`
	SourceWatermark int64  `json:"source_watermark"`
}

type ReadCurationJobByDigestWatermarkRow struct {
	ID                      string         `json:"id"`
	WorkspaceID             string         `json:"workspace_id"`
	Reason                  string         `json:"reason"`
	ReasonFlags             string         `json:"reason_flags"`
	Priority                int64          `json:"priority"`
	SessionDigest           []byte         `json:"session_digest"`
	SourceWatermark         int64          `json:"source_watermark"`
	ThreadLocatorCiphertext []byte         `json:"thread_locator_ciphertext"`
	SnapshotCiphertext      []byte         `json:"snapshot_ciphertext"`
	State                   string         `json:"state"`
	AttemptCount            int64          `json:"attempt_count"`
	NextAttemptAt           sql.NullString `json:"next_attempt_at"`
	ExpiresAt               string         `json:"expires_at"`
	ProviderName            string         `json:"provider_name"`
	SafeErrorClass          string         `json:"safe_error_class"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

func (q *Queries) ReadCurationJobByDigestWatermark(ctx context.Context, arg ReadCurationJobByDigestWatermarkParams) (ReadCurationJobByDigestWatermarkRow, error) {
	row := q.db.QueryRowContext(ctx, readCurationJobByDigestWatermark, arg.SessionDigest, arg.SourceWatermark)
	var i ReadCurationJobByDigestWatermarkRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Reason,
		&i.ReasonFlags,
		&i.Priority,
		&i.SessionDigest,
		&i.SourceWatermark,
		&i.ThreadLocatorCiphertext,
		&i.SnapshotCiphertext,
		&i.State,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ExpiresAt,
		&i.ProviderName,
		&i.SafeErrorClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readCurationJobByID = `-- name: ReadCurationJobByID :one
SELECT id, workspace_id, reason, reason_flags, priority, session_digest,
       source_watermark, thread_locator_ciphertext, snapshot_ciphertext,
       state, attempt_count, next_attempt_at, expires_at, provider_name,
       safe_error_class, created_at, updated_at
FROM curation_jobs
WHERE id = ?
`

type ReadCurationJobByIDRow struct {
	ID                      string         `json:"id"`
	WorkspaceID             string         `json:"workspace_id"`
	Reason                  string         `json:"reason"`
	ReasonFlags             string         `json:"reason_flags"`
	Priority                int64          `json:"priority"`
	SessionDigest           []byte         `json:"session_digest"`
	SourceWatermark         int64          `json:"source_watermark"`
	ThreadLocatorCiphertext []byte         `json:"thread_locator_ciphertext"`
	SnapshotCiphertext      []byte         `json:"snapshot_ciphertext"`
	State                   string         `json:"state"`
	AttemptCount            int64          `json:"attempt_count"`
	NextAttemptAt           sql.NullString `json:"next_attempt_at"`
	ExpiresAt               string         `json:"expires_at"`
	ProviderName            string         `json:"provider_name"`
	SafeErrorClass          string         `json:"safe_error_class"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

func (q *Queries) ReadCurationJobByID(ctx context.Context, id string) (ReadCurationJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, readCurationJobByID, id)
	var i ReadCurationJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Reason,
		&i.ReasonFlags,
		&i.Priority,
		&i.SessionDigest,
		&i.SourceWatermark,
		&i.ThreadLocatorCiphertext,
		&i.SnapshotCiphertext,
		&i.State,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ExpiresAt,
		&i.ProviderName,
		&i.SafeErrorClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readCurationSessionCounter = `-- name: ReadCurationSessionCounter :one
SELECT session_digest, prompt_count, last_watermark, expires_at
FROM curation_session_counters
WHERE session_digest = ?
`

func (q *Queries) ReadCurationSessionCounter(ctx context.Context, sessionDigest []byte) (CurationSessionCounter, error) {
	row := q.db.QueryRowContext(ctx, readCurationSessionCounter, sessionDigest)
	var i CurationSessionCounter
	err := row.Scan(
		&i.SessionDigest,
		&i.PromptCount,
		&i.LastWatermark,
		&i.ExpiresAt,
	)
	return i, err
}

const retryCurationJob = `-- name: RetryCurationJob :execrows
UPDATE curation_jobs
SET state = 'retry_wait', attempt_count = ?, next_attempt_at = ?,
    safe_error_class = ?, updated_at = ?
WHERE id = ? AND state = 'running'
`

type RetryCurationJobParams struct {
	AttemptCount   int64          `json:"attempt_count"`
	NextAttemptAt  sql.NullString `json:"next_attempt_at"`
	SafeErrorClass string         `json:"safe_error_class"`
	UpdatedAt      string         `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) RetryCurationJob(ctx context.Context, arg RetryCurationJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryCurationJob,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.SafeErrorClass,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCurationJobCoalesced = `-- name: UpdateCurationJobCoalesced :exec
UPDATE curation_jobs
SET reason = ?,
    reason_flags = ?,
    priority = ?,
    thread_locator_ciphertext = ?,
    snapshot_ciphertext = ?,
    expires_at = ?,
    state = CASE WHEN state = 'retry_wait' THEN 'pending' ELSE state END,
    next_attempt_at = CASE WHEN state = 'retry_wait' THEN NULL ELSE next_attempt_at END,
    updated_at = ?
WHERE id = ?
`

type UpdateCurationJobCoalescedParams struct {
	Reason                  string `json:"reason"`
	ReasonFlags             string `json:"reason_flags"`
	Priority                int64  `json:"priority"`
	ThreadLocatorCiphertext []byte `json:"thread_locator_ciphertext"`
	SnapshotCiphertext      []byte `json:"snapshot_ciphertext"`
	ExpiresAt               string `json:"expires_at"`
	UpdatedAt               string `json:"updated_at"`
	ID                      string `json:"id"`
}

func (q *Queries) UpdateCurationJobCoalesced(ctx context.Context, arg UpdateCurationJobCoalescedParams) error {
	_, err := q.db.ExecContext(ctx, updateCurationJobCoalesced,
		arg.Reason,
		arg.ReasonFlags,
		arg.Priority,
		arg.ThreadLocatorCiphertext,
		arg.SnapshotCiphertext,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
