// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: maintenance.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertPurgeOperation = `-- name: InsertPurgeOperation :exec
INSERT INTO purge_operations(
    id, operation_kind, memory_id, workspace_id, expected_revision_id, phase,
    receipt_digest, receipt_consumed, inventory_watermark, resume_cursor,
    safe_error, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPurgeOperationParams struct {
	ID                 string         `json:"id"`
	OperationKind      string         `json:"operation_kind"`
	MemoryID           sql.NullString `json:"memory_id"`
	WorkspaceID        sql.NullString `json:"workspace_id"`
	ExpectedRevisionID sql.NullString `json:"expected_revision_id"`
	Phase              string         `json:"phase"`
	ReceiptDigest      []byte         `json:"receipt_digest"`
	ReceiptConsumed    int64          `json:"receipt_consumed"`
	InventoryWatermark int64          `json:"inventory_watermark"`
	ResumeCursor       string         `json:"resume_cursor"`
	SafeError          string         `json:"safe_error"`
	CreatedAt          string         `json:"created_at"`
	UpdatedAt          string         `json:"updated_at"`
}

func (q *Queries) InsertPurgeOperation(ctx context.Context, arg InsertPurgeOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertPurgeOperation,
		arg.ID,
		arg.OperationKind,
		arg.MemoryID,
		arg.WorkspaceID,
		arg.ExpectedRevisionID,
		arg.Phase,
		arg.ReceiptDigest,
		arg.ReceiptConsumed,
		arg.InventoryWatermark,
		arg.ResumeCursor,
		arg.SafeError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const readActivationJournal = `-- name: ReadActivationJournal :one
SELECT id, version, active_generation, candidate_generation, phase,
    revision_watermark, candidate_rule_fingerprint, last_processed_id,
    live_mutation_started, quarantined_count, fts_removed_count,
    outbox_added_count, projected_count, resume_cursor, safe_error, updated_at
FROM rule_activation_journal WHERE id = 1
`

func (q *Queries) ReadActivationJournal(ctx context.Context) (RuleActivationJournal, error) {
	row := q.db.QueryRowContext(ctx, readActivationJournal)
	var i RuleActivationJournal
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ActiveGeneration,
		&i.CandidateGeneration,
		&i.Phase,
		&i.RevisionWatermark,
		&i.CandidateRuleFingerprint,
		&i.LastProcessedID,
		&i.LiveMutationStarted,
		&i.QuarantinedCount,
		&i.FtsRemovedCount,
		&i.OutboxAddedCount,
		&i.ProjectedCount,
		&i.ResumeCursor,
		&i.SafeError,
		&i.UpdatedAt,
	)
	return i, err
}

const storeActivationJournal = `-- name: StoreActivationJournal :execrows
UPDATE rule_activation_journal
SET version = version + 1,
    active_generation = ?, candidate_generation = ?, phase = ?,
    revision_watermark = ?, candidate_rule_fingerprint = ?,
    last_processed_id = ?, live_mutation_started = ?, quarantined_count = ?,
    fts_removed_count = ?, outbox_added_count = ?, projected_count = ?,
    resume_cursor = ?, safe_error = ?, updated_at = ?
WHERE id = 1 AND version = ?
`

type StoreActivationJournalParams struct {
	ActiveGeneration         string         `json:"active_generation"`
	CandidateGeneration      sql.NullString `json:"candidate_generation"`
	Phase                    string         `json:"phase"`
	RevisionWatermark        int64          `json:"revision_watermark"`
	CandidateRuleFingerprint string         `json:"candidate_rule_fingerprint"`
	LastProcessedID          string         `json:"last_processed_id"`
	LiveMutationStarted      int64          `json:"live_mutation_started"`
	QuarantinedCount         int64          `json:"quarantined_count"`
	FtsRemovedCount          int64          `json:"fts_removed_count"`
	OutboxAddedCount         int64          `json:"outbox_added_count"`
	ProjectedCount           int64          `json:"projected_count"`
	ResumeCursor             string         `json:"resume_cursor"`
	SafeError                string         `json:"safe_error"`
	UpdatedAt                string         `json:"updated_at"`
	Version                  int64          `json:"version"`
}

func (q *Queries) StoreActivationJournal(ctx context.Context, arg StoreActivationJournalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, storeActivationJournal,
		arg.ActiveGeneration,
		arg.CandidateGeneration,
		arg.Phase,
		arg.RevisionWatermark,
		arg.CandidateRuleFingerprint,
		arg.LastProcessedID,
		arg.LiveMutationStarted,
		arg.QuarantinedCount,
		arg.FtsRemovedCount,
		arg.OutboxAddedCount,
		arg.ProjectedCount,
		arg.ResumeCursor,
		arg.SafeError,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
