// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: memory.sql

package sqlc

import (
	"context"
	"database/sql"
)

const appendOutbox = `-- name: AppendOutbox :exec
INSERT INTO outbox(scope_id, revision_watermark, created_at)
VALUES (?, ?, ?)
ON CONFLICT(scope_id, revision_watermark) DO NOTHING
`

type AppendOutboxParams struct {
	ScopeID           string `json:"scope_id"`
	RevisionWatermark int64  `json:"revision_watermark"`
	CreatedAt         string `json:"created_at"`
}

func (q *Queries) AppendOutbox(ctx context.Context, arg AppendOutboxParams) error {
	_, err := q.db.ExecContext(ctx, appendOutbox, arg.ScopeID, arg.RevisionWatermark, arg.CreatedAt)
	return err
}

const createMemory = `-- name: CreateMemory :exec
INSERT INTO memories (
    id, workspace_id, user_global, kind, trust, lifecycle, current_revision_id,
    pinned, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMemoryParams struct {
	ID                string         `json:"id"`
	WorkspaceID       sql.NullString `json:"workspace_id"`
	UserGlobal        int64          `json:"user_global"`
	Kind              string         `json:"kind"`
	Trust             string         `json:"trust"`
	Lifecycle         string         `json:"lifecycle"`
	CurrentRevisionID sql.NullString `json:"current_revision_id"`
	Pinned            int64          `json:"pinned"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) error {
	_, err := q.db.ExecContext(ctx, createMemory,
		arg.ID,
		arg.WorkspaceID,
		arg.UserGlobal,
		arg.Kind,
		arg.Trust,
		arg.Lifecycle,
		arg.CurrentRevisionID,
		arg.Pinned,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMemoryRevision = `-- name: CreateMemoryRevision :exec
INSERT INTO memory_revisions (
    id, memory_id, revision_number, kind, title, content, tags_json,
    resolution_state, trust, lifecycle, provenance_actor, provenance_source,
    provenance_labels_json, source_locator, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMemoryRevisionParams struct {
	ID                   string         `json:"id"`
	MemoryID             string         `json:"memory_id"`
	RevisionNumber       int64          `json:"revision_number"`
	Kind                 string         `json:"kind"`
	Title                string         `json:"title"`
	Content              string         `json:"content"`
	TagsJson             string         `json:"tags_json"`
	ResolutionState      sql.NullString `json:"resolution_state"`
	Trust                string         `json:"trust"`
	Lifecycle            string         `json:"lifecycle"`
	ProvenanceActor      string         `json:"provenance_actor"`
	ProvenanceSource     string         `json:"provenance_source"`
	ProvenanceLabelsJson string         `json:"provenance_labels_json"`
	SourceLocator        string         `json:"source_locator"`
	CreatedAt            string         `json:"created_at"`
}

func (q *Queries) CreateMemoryRevision(ctx context.Context, arg CreateMemoryRevisionParams) error {
	_, err := q.db.ExecContext(ctx, createMemoryRevision,
		arg.ID,
		arg.MemoryID,
		arg.RevisionNumber,
		arg.Kind,
		arg.Title,
		arg.Content,
		arg.TagsJson,
		arg.ResolutionState,
		arg.Trust,
		arg.Lifecycle,
		arg.ProvenanceActor,
		arg.ProvenanceSource,
		arg.ProvenanceLabelsJson,
		arg.SourceLocator,
		arg.CreatedAt,
	)
	return err
}

const deleteAllFTSRows = `-- name: DeleteAllFTSRows :exec
DELETE FROM memory_fts
`

func (q *Queries) DeleteAllFTSRows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFTSRows)
	return err
}

const deleteFTSRow = `-- name: DeleteFTSRow :exec
DELETE FROM memory_fts WHERE memory_id = ?
`

func (q *Queries) DeleteFTSRow(ctx context.Context, memoryID string) error {
	_, err := q.db.ExecContext(ctx, deleteFTSRow, memoryID)
	return err
}

const insertEligibleFTSRow = `-- name: InsertEligibleFTSRow :exec
INSERT INTO memory_fts(title, content, tags, memory_id)
SELECT revisions.title, revisions.content, revisions.tags_json, memories.id
FROM memories
JOIN memory_revisions AS revisions ON revisions.id = memories.current_revision_id
WHERE memories.id = ?
  AND memories.trust = 'verified'
  AND memories.lifecycle = 'active'
  AND revisions.trust = 'verified'
  AND revisions.lifecycle = 'active'
`

func (q *Queries) InsertEligibleFTSRow(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, insertEligibleFTSRow, id)
	return err
}

const moveCurrentRevision = `-- name: MoveCurrentRevision :execrows
UPDATE memories
SET current_revision_id = ?, kind = ?, trust = ?, lifecycle = ?, updated_at = ?
WHERE id = ? AND current_revision_id = ?
`

type MoveCurrentRevisionParams struct {
	CurrentRevisionID   sql.NullString `json:"current_revision_id"`
	Kind                string         `json:"kind"`
	Trust               string         `json:"trust"`
	Lifecycle           string         `json:"lifecycle"`
	UpdatedAt           string         `json:"updated_at"`
	ID                  string         `json:"id"`
	CurrentRevisionID_2 sql.NullString `json:"current_revision_id_2"`
}

func (q *Queries) MoveCurrentRevision(ctx context.Context, arg MoveCurrentRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveCurrentRevision,
		arg.CurrentRevisionID,
		arg.Kind,
		arg.Trust,
		arg.Lifecycle,
		arg.UpdatedAt,
		arg.ID,
		arg.CurrentRevisionID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const moveInitialCurrentRevision = `-- name: MoveInitialCurrentRevision :execrows
UPDATE memories
SET current_revision_id = ?, kind = ?, trust = ?, lifecycle = ?, updated_at = ?
WHERE id = ? AND current_revision_id IS NULL
`

type MoveInitialCurrentRevisionParams struct {
	CurrentRevisionID sql.NullString `json:"current_revision_id"`
	Kind              string         `json:"kind"`
	Trust             string         `json:"trust"`
	Lifecycle         string         `json:"lifecycle"`
	UpdatedAt         string         `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) MoveInitialCurrentRevision(ctx context.Context, arg MoveInitialCurrentRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveInitialCurrentRevision,
		arg.CurrentRevisionID,
		arg.Kind,
		arg.Trust,
		arg.Lifecycle,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const readCurrent = `-- name: ReadCurrent :one
SELECT
    memories.id, memories.workspace_id, memories.user_global, memories.kind,
    memories.trust, memories.lifecycle, memories.current_revision_id,
    memories.pinned, memories.created_at, memories.updated_at,
    revisions.id, revisions.revision_number, revisions.kind, revisions.title,
    revisions.content, revisions.tags_json, revisions.resolution_state,
    revisions.trust, revisions.lifecycle, revisions.provenance_actor,
    revisions.provenance_source, revisions.provenance_labels_json,
    revisions.source_locator, revisions.created_at
FROM memories
JOIN memory_revisions AS revisions ON revisions.id = memories.current_revision_id
WHERE memories.id = ?
`

type ReadCurrentRow struct {
	ID                   string         `json:"id"`
	WorkspaceID          sql.NullString `json:"workspace_id"`
	UserGlobal           int64          `json:"user_global"`
	Kind                 string         `json:"kind"`
	Trust                string         `json:"trust"`
	Lifecycle            string         `json:"lifecycle"`
	CurrentRevisionID    sql.NullString `json:"current_revision_id"`
	Pinned               int64          `json:"pinned"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	ID_2                 string         `json:"id_2"`
	RevisionNumber       int64          `json:"revision_number"`
	Kind_2               string         `json:"kind_2"`
	Title                string         `json:"title"`
	Content              string         `json:"content"`
	TagsJson             string         `json:"tags_json"`
	ResolutionState      sql.NullString `json:"resolution_state"`
	Trust_2              string         `json:"trust_2"`
	Lifecycle_2          string         `json:"lifecycle_2"`
	ProvenanceActor      string         `json:"provenance_actor"`
	ProvenanceSource     string         `json:"provenance_source"`
	ProvenanceLabelsJson string         `json:"provenance_labels_json"`
	SourceLocator        string         `json:"source_locator"`
	CreatedAt_2          string         `json:"created_at_2"`
}

func (q *Queries) ReadCurrent(ctx context.Context, id string) (ReadCurrentRow, error) {
	row := q.db.QueryRowContext(ctx, readCurrent, id)
	var i ReadCurrentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserGlobal,
		&i.Kind,
		&i.Trust,
		&i.Lifecycle,
		&i.CurrentRevisionID,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.RevisionNumber,
		&i.Kind_2,
		&i.Title,
		&i.Content,
		&i.TagsJson,
		&i.ResolutionState,
		&i.Trust_2,
		&i.Lifecycle_2,
		&i.ProvenanceActor,
		&i.ProvenanceSource,
		&i.ProvenanceLabelsJson,
		&i.SourceLocator,
		&i.CreatedAt_2,
	)
	return i, err
}

const rebuildEligibleFTSRows = `-- name: RebuildEligibleFTSRows :exec
INSERT INTO memory_fts(title, content, tags, memory_id)
SELECT revisions.title, revisions.content, revisions.tags_json, memories.id
FROM memories
JOIN memory_revisions AS revisions ON revisions.id = memories.current_revision_id
WHERE memories.trust = 'verified'
  AND memories.lifecycle = 'active'
  AND revisions.trust = 'verified'
  AND revisions.lifecycle = 'active'
ORDER BY memories.id
`

func (q *Queries) RebuildEligibleFTSRows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rebuildEligibleFTSRows)
	return err
}
