// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type DeletionReceipt struct {
	ID               string `json:"id"`
	OperationID      string `json:"operation_id"`
	MemoryID         string `json:"memory_id"`
	CompletedAt      string `json:"completed_at"`
	SafeMetadataJson string `json:"safe_metadata_json"`
}

type IdempotencyRequest struct {
	Caller         string `json:"caller"`
	Operation      string `json:"operation"`
	KeyDigest      []byte `json:"key_digest"`
	RequestDigest  []byte `json:"request_digest"`
	TargetIdsJson  string `json:"target_ids_json"`
	SafeResultJson string `json:"safe_result_json"`
	CreatedAt      string `json:"created_at"`
	ExpiresAt      string `json:"expires_at"`
}

type ManagedBackup struct {
	ID                        string `json:"id"`
	Path                      string `json:"path"`
	Sha256                    string `json:"sha256"`
	Mode                      int64  `json:"mode"`
	CreationCause             string `json:"creation_cause"`
	SchemaVersion             int64  `json:"schema_version"`
	DatabaseRevisionWatermark int64  `json:"database_revision_watermark"`
	Lifecycle                 string `json:"lifecycle"`
	OwnerID                   string `json:"owner_id"`
	KeyVersion                int64  `json:"key_version"`
	CreatedAt                 string `json:"created_at"`
	UpdatedAt                 string `json:"updated_at"`
}

type Memory struct {
	ID                string         `json:"id"`
	WorkspaceID       sql.NullString `json:"workspace_id"`
	UserGlobal        int64          `json:"user_global"`
	Kind              string         `json:"kind"`
	Trust             string         `json:"trust"`
	Lifecycle         string         `json:"lifecycle"`
	CurrentRevisionID sql.NullString `json:"current_revision_id"`
	Pinned            int64          `json:"pinned"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type MemoryAlias struct {
	AliasMemoryID     string `json:"alias_memory_id"`
	CanonicalMemoryID string `json:"canonical_memory_id"`
	CreatedAt         string `json:"created_at"`
}

type MemoryFt struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Tags     string `json:"tags"`
	MemoryID string `json:"memory_id"`
}

type MemoryRevision struct {
	ID                   string         `json:"id"`
	MemoryID             string         `json:"memory_id"`
	RevisionNumber       int64          `json:"revision_number"`
	Kind                 string         `json:"kind"`
	Title                string         `json:"title"`
	Content              string         `json:"content"`
	TagsJson             string         `json:"tags_json"`
	ResolutionState      sql.NullString `json:"resolution_state"`
	Trust                string         `json:"trust"`
	Lifecycle            string         `json:"lifecycle"`
	ProvenanceActor      string         `json:"provenance_actor"`
	ProvenanceSource     string         `json:"provenance_source"`
	ProvenanceLabelsJson string         `json:"provenance_labels_json"`
	SourceLocator        string         `json:"source_locator"`
	CreatedAt            string         `json:"created_at"`
}

type MigrationJournal struct {
	ID               int64          `json:"id"`
	TargetVersion    int64          `json:"target_version"`
	CurrentVersion   int64          `json:"current_version"`
	FailedVersion    sql.NullInt64  `json:"failed_version"`
	CompletedVersion sql.NullInt64  `json:"completed_version"`
	BackupID         sql.NullString `json:"backup_id"`
	SafeError        string         `json:"safe_error"`
	StartedAt        string         `json:"started_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Outbox struct {
	ID                int64          `json:"id"`
	ScopeID           string         `json:"scope_id"`
	RevisionWatermark int64          `json:"revision_watermark"`
	AttemptCount      int64          `json:"attempt_count"`
	NextAttemptAt     sql.NullString `json:"next_attempt_at"`
	SafeError         string         `json:"safe_error"`
	CreatedAt         string         `json:"created_at"`
}

type ProjectionState struct {
	ScopeID           string         `json:"scope_id"`
	RevisionWatermark int64          `json:"revision_watermark"`
	Status            string         `json:"status"`
	Fingerprint       string         `json:"fingerprint"`
	AttemptCount      int64          `json:"attempt_count"`
	NextAttemptAt     sql.NullString `json:"next_attempt_at"`
	SafeError         string         `json:"safe_error"`
	UpdatedAt         string         `json:"updated_at"`
}

type PurgeOperation struct {
	ID                 string         `json:"id"`
	OperationKind      string         `json:"operation_kind"`
	MemoryID           sql.NullString `json:"memory_id"`
	WorkspaceID        sql.NullString `json:"workspace_id"`
	ExpectedRevisionID sql.NullString `json:"expected_revision_id"`
	Phase              string         `json:"phase"`
	ReceiptDigest      []byte         `json:"receipt_digest"`
	ReceiptConsumed    int64          `json:"receipt_consumed"`
	InventoryWatermark int64          `json:"inventory_watermark"`
	ResumeCursor       string         `json:"resume_cursor"`
	SafeError          string         `json:"safe_error"`
	CreatedAt          string         `json:"created_at"`
	UpdatedAt          string         `json:"updated_at"`
	CompletedAt        sql.NullString `json:"completed_at"`
}

type RuleActivationJournal struct {
	ID                       int64          `json:"id"`
	Version                  int64          `json:"version"`
	ActiveGeneration         string         `json:"active_generation"`
	CandidateGeneration      sql.NullString `json:"candidate_generation"`
	Phase                    string         `json:"phase"`
	RevisionWatermark        int64          `json:"revision_watermark"`
	CandidateRuleFingerprint string         `json:"candidate_rule_fingerprint"`
	LastProcessedID          string         `json:"last_processed_id"`
	LiveMutationStarted      int64          `json:"live_mutation_started"`
	QuarantinedCount         int64          `json:"quarantined_count"`
	FtsRemovedCount          int64          `json:"fts_removed_count"`
	OutboxAddedCount         int64          `json:"outbox_added_count"`
	ProjectedCount           int64          `json:"projected_count"`
	ResumeCursor             string         `json:"resume_cursor"`
	SafeError                string         `json:"safe_error"`
	UpdatedAt                string         `json:"updated_at"`
}

type SkillPromotion struct {
	ID                string `json:"id"`
	MemoryID          string `json:"memory_id"`
	RevisionID        string `json:"revision_id"`
	Actor             string `json:"actor"`
	OutputPath        string `json:"output_path"`
	OutputFingerprint string `json:"output_fingerprint"`
	CreatedAt         string `json:"created_at"`
}

type UsageDaily struct {
	MemoryID      string `json:"memory_id"`
	Day           string `json:"day"`
	Hits          int64  `json:"hits"`
	Opportunities int64  `json:"opportunities"`
}

type UsageLifetime struct {
	MemoryID      string `json:"memory_id"`
	Hits          int64  `json:"hits"`
	Opportunities int64  `json:"opportunities"`
}

type UsageSessionHit struct {
	MemoryID         string `json:"memory_id"`
	ConsumerDigest   []byte `json:"consumer_digest"`
	FirstDeliveredAt string `json:"first_delivered_at"`
}

type Workspace struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	RevisionWatermark int64  `json:"revision_watermark"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type WorkspaceBinding struct {
	BindingKey           string `json:"binding_key"`
	WorkspaceID          string `json:"workspace_id"`
	BindingKind          string `json:"binding_kind"`
	FirstInferenceWarned int64  `json:"first_inference_warned"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

type WorkspaceRedirect struct {
	SourceWorkspaceID string `json:"source_workspace_id"`
	TargetWorkspaceID string `json:"target_workspace_id"`
	CreatedAt         string `json:"created_at"`
}
