// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projection.sql

package sqlc

import (
	"context"
	"database/sql"
)

const acknowledgeProjection = `-- name: AcknowledgeProjection :exec
DELETE FROM outbox
WHERE scope_id = ? AND revision_watermark <= ?
`

type AcknowledgeProjectionParams struct {
	ScopeID           string `json:"scope_id"`
	RevisionWatermark int64  `json:"revision_watermark"`
}

func (q *Queries) AcknowledgeProjection(ctx context.Context, arg AcknowledgeProjectionParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeProjection, arg.ScopeID, arg.RevisionWatermark)
	return err
}

const countProjectionBlockers = `-- name: CountProjectionBlockers :one
SELECT count(*)
FROM projection_state
WHERE status IN ('drifted', 'blocked', 'rebuilding')
`

func (q *Queries) CountProjectionBlockers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectionBlockers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProjectionMemoryIDs = `-- name: ListProjectionMemoryIDs :many
SELECT memories.id
FROM memories
JOIN memory_revisions AS revisions ON revisions.id = memories.current_revision_id
WHERE ((? = 'global' AND memories.user_global = 1) OR memories.workspace_id = ?)
  AND memories.trust = 'verified'
  AND memories.lifecycle = 'active'
  AND revisions.trust = 'verified'
  AND revisions.lifecycle = 'active'
ORDER BY memories.id
`

type ListProjectionMemoryIDsParams struct {
	Column1     interface{}    `json:"column_1"`
	WorkspaceID sql.NullString `json:"workspace_id"`
}

func (q *Queries) ListProjectionMemoryIDs(ctx context.Context, arg ListProjectionMemoryIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectionMemoryIDs, arg.Column1, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingProjection = `-- name: PendingProjection :many
SELECT scope_id, revision_watermark
FROM outbox
WHERE scope_id = ?
  AND (next_attempt_at IS NULL OR next_attempt_at <= ?)
ORDER BY revision_watermark, id
`

type PendingProjectionParams struct {
	ScopeID       string         `json:"scope_id"`
	NextAttemptAt sql.NullString `json:"next_attempt_at"`
}

type PendingProjectionRow struct {
	ScopeID           string `json:"scope_id"`
	RevisionWatermark int64  `json:"revision_watermark"`
}

func (q *Queries) PendingProjection(ctx context.Context, arg PendingProjectionParams) ([]PendingProjectionRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingProjection, arg.ScopeID, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingProjectionRow{}
	for rows.Next() {
		var i PendingProjectionRow
		if err := rows.Scan(&i.ScopeID, &i.RevisionWatermark); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readProjectionState = `-- name: ReadProjectionState :one
SELECT scope_id, revision_watermark, status, fingerprint, attempt_count,
    next_attempt_at, safe_error, updated_at
FROM projection_state
WHERE scope_id = ?
`

func (q *Queries) ReadProjectionState(ctx context.Context, scopeID string) (ProjectionState, error) {
	row := q.db.QueryRowContext(ctx, readProjectionState, scopeID)
	var i ProjectionState
	err := row.Scan(
		&i.ScopeID,
		&i.RevisionWatermark,
		&i.Status,
		&i.Fingerprint,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SafeError,
		&i.UpdatedAt,
	)
	return i, err
}

const recordProjectionFailure = `-- name: RecordProjectionFailure :exec
INSERT INTO outbox(
    scope_id, revision_watermark, attempt_count, next_attempt_at, safe_error, created_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(scope_id, revision_watermark) DO UPDATE SET
    attempt_count = excluded.attempt_count,
    next_attempt_at = excluded.next_attempt_at,
    safe_error = excluded.safe_error
`

type RecordProjectionFailureParams struct {
	ScopeID           string         `json:"scope_id"`
	RevisionWatermark int64          `json:"revision_watermark"`
	AttemptCount      int64          `json:"attempt_count"`
	NextAttemptAt     sql.NullString `json:"next_attempt_at"`
	SafeError         string         `json:"safe_error"`
	CreatedAt         string         `json:"created_at"`
}

func (q *Queries) RecordProjectionFailure(ctx context.Context, arg RecordProjectionFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordProjectionFailure,
		arg.ScopeID,
		arg.RevisionWatermark,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.SafeError,
		arg.CreatedAt,
	)
	return err
}

const resetProjectionState = `-- name: ResetProjectionState :exec
UPDATE projection_state
SET attempt_count = 0, next_attempt_at = NULL, safe_error = ?, updated_at = ?
WHERE scope_id = ?
`

type ResetProjectionStateParams struct {
	SafeError string `json:"safe_error"`
	UpdatedAt string `json:"updated_at"`
	ScopeID   string `json:"scope_id"`
}

func (q *Queries) ResetProjectionState(ctx context.Context, arg ResetProjectionStateParams) error {
	_, err := q.db.ExecContext(ctx, resetProjectionState, arg.SafeError, arg.UpdatedAt, arg.ScopeID)
	return err
}

const upsertProjectionState = `-- name: UpsertProjectionState :exec
INSERT INTO projection_state(
    scope_id, revision_watermark, status, fingerprint, updated_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(scope_id) DO UPDATE SET
    revision_watermark = excluded.revision_watermark,
    status = excluded.status,
    fingerprint = excluded.fingerprint,
    updated_at = excluded.updated_at
`

type UpsertProjectionStateParams struct {
	ScopeID           string `json:"scope_id"`
	RevisionWatermark int64  `json:"revision_watermark"`
	Status            string `json:"status"`
	Fingerprint       string `json:"fingerprint"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) UpsertProjectionState(ctx context.Context, arg UpsertProjectionStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectionState,
		arg.ScopeID,
		arg.RevisionWatermark,
		arg.Status,
		arg.Fingerprint,
		arg.UpdatedAt,
	)
	return err
}
