// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	AppendOutbox(ctx context.Context, arg AppendOutboxParams) error
	CreateMemory(ctx context.Context, arg CreateMemoryParams) error
	CreateMemoryRevision(ctx context.Context, arg CreateMemoryRevisionParams) error
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteAllFTSRows(ctx context.Context) error
	DeleteFTSRow(ctx context.Context, memoryID string) error
	DeleteUsageBefore(ctx context.Context, day string) (int64, error)
	InsertEligibleFTSRow(ctx context.Context, id string) error
	InsertPurgeOperation(ctx context.Context, arg InsertPurgeOperationParams) error
	MoveCurrentRevision(ctx context.Context, arg MoveCurrentRevisionParams) (int64, error)
	MoveInitialCurrentRevision(ctx context.Context, arg MoveInitialCurrentRevisionParams) (int64, error)
	ReadActivationJournal(ctx context.Context) (RuleActivationJournal, error)
	ReadCurrent(ctx context.Context, id string) (ReadCurrentRow, error)
	ReadWorkspace(ctx context.Context, id string) (Workspace, error)
	RebuildEligibleFTSRows(ctx context.Context) error
	StoreActivationJournal(ctx context.Context, arg StoreActivationJournalParams) (int64, error)
	UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error
	UpsertUsageLifetime(ctx context.Context, arg UpsertUsageLifetimeParams) error
	UpsertWorkspaceBinding(ctx context.Context, arg UpsertWorkspaceBindingParams) error
}

var _ Querier = (*Queries)(nil)
