// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: usage.sql

package sqlc

import (
	"context"
)

const deleteUsageBefore = `-- name: DeleteUsageBefore :execrows
DELETE FROM usage_daily WHERE day < ?
`

func (q *Queries) DeleteUsageBefore(ctx context.Context, day string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUsageBefore, day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertUsageDaily = `-- name: UpsertUsageDaily :exec
INSERT INTO usage_daily(memory_id, day, hits, opportunities)
VALUES (?, ?, ?, ?)
ON CONFLICT(memory_id, day) DO UPDATE SET
    hits = usage_daily.hits + excluded.hits,
    opportunities = usage_daily.opportunities + excluded.opportunities
`

type UpsertUsageDailyParams struct {
	MemoryID      string `json:"memory_id"`
	Day           string `json:"day"`
	Hits          int64  `json:"hits"`
	Opportunities int64  `json:"opportunities"`
}

func (q *Queries) UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertUsageDaily,
		arg.MemoryID,
		arg.Day,
		arg.Hits,
		arg.Opportunities,
	)
	return err
}

const upsertUsageLifetime = `-- name: UpsertUsageLifetime :exec
INSERT INTO usage_lifetime(memory_id, hits, opportunities)
VALUES (?, ?, ?)
ON CONFLICT(memory_id) DO UPDATE SET
    hits = usage_lifetime.hits + excluded.hits,
    opportunities = usage_lifetime.opportunities + excluded.opportunities
`

type UpsertUsageLifetimeParams struct {
	MemoryID      string `json:"memory_id"`
	Hits          int64  `json:"hits"`
	Opportunities int64  `json:"opportunities"`
}

func (q *Queries) UpsertUsageLifetime(ctx context.Context, arg UpsertUsageLifetimeParams) error {
	_, err := q.db.ExecContext(ctx, upsertUsageLifetime, arg.MemoryID, arg.Hits, arg.Opportunities)
	return err
}
