// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspace.sql

package sqlc

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces(id, name, revision_watermark, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	RevisionWatermark int64  `json:"revision_watermark"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.RevisionWatermark,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const readWorkspace = `-- name: ReadWorkspace :one
SELECT id, name, revision_watermark, created_at, updated_at
FROM workspaces WHERE id = ?
`

func (q *Queries) ReadWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, readWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RevisionWatermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceBinding = `-- name: UpsertWorkspaceBinding :exec
INSERT INTO workspace_bindings(
    binding_key, workspace_id, binding_kind, first_inference_warned, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(binding_key) DO UPDATE SET
    workspace_id = excluded.workspace_id,
    binding_kind = excluded.binding_kind,
    first_inference_warned = excluded.first_inference_warned,
    updated_at = excluded.updated_at
`

type UpsertWorkspaceBindingParams struct {
	BindingKey           string `json:"binding_key"`
	WorkspaceID          string `json:"workspace_id"`
	BindingKind          string `json:"binding_kind"`
	FirstInferenceWarned int64  `json:"first_inference_warned"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

func (q *Queries) UpsertWorkspaceBinding(ctx context.Context, arg UpsertWorkspaceBindingParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspaceBinding,
		arg.BindingKey,
		arg.WorkspaceID,
		arg.BindingKind,
		arg.FirstInferenceWarned,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
